// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// maxmarg_DeepState_TestHarness_generation.cpp and maxmarg_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

IntegerMatrix maxmarg(const NumericVector& prob_array, const double minprob, const double tol);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector prob_array  = RcppDeepState_NumericVector();
  qs::c_qsave(prob_array,"/home/akhila/fuzzer_packages/fuzzedpackages/qtl2/inst/testfiles/maxmarg/inputs/prob_array.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "prob_array values: "<< prob_array << std::endl;
  NumericVector minprob(1);
  minprob[0]  = RcppDeepState_double();
  qs::c_qsave(minprob,"/home/akhila/fuzzer_packages/fuzzedpackages/qtl2/inst/testfiles/maxmarg/inputs/minprob.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "minprob values: "<< minprob << std::endl;
  NumericVector tol(1);
  tol[0]  = RcppDeepState_double();
  qs::c_qsave(tol,"/home/akhila/fuzzer_packages/fuzzedpackages/qtl2/inst/testfiles/maxmarg/inputs/tol.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "tol values: "<< tol << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    maxmarg(prob_array,minprob[0],tol[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
