// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// cpp_log0const_DeepState_TestHarness_generation.cpp and cpp_log0const_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

arma::mat cpp_log0const(const arma::mat& x, const double& constant);

TEST(,){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  std::ofstream x_stream;
  arma::mat x  = RcppDeepState_mat();
  x_stream.open("/home/akhila/fuzzer_packages/fuzzedpackages/exdex/inst/testfiles/cpp_log0const/inputs/x");
  x_stream << x;
  std::cout << "x values: "<< x << std::endl;
  x_stream.close();
  NumericVector ant(1);
  ant[0]  = RcppDeepState_double();
  std::string constant_t = "/home/akhila/fuzzer_packages/fuzzedpackages/exdex/inst/testfiles/cpp_log0const/libFuzzer_cpp_log0const/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_constant.qs";
  qs::c_qsave(constant,constant_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "constant values: "<< constant << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    cpp_log0const(x,constant[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
