// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// sample_probit_DeepState_TestHarness_generation.cpp and sample_probit_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

List sample_probit(arma::mat y_matrix, arma::mat y_categ, arma::mat X, arma::mat beta_old, int nsave, int nburn, double A0, double d0, double D0, double G0, int BOOST, int verbose);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  std::ofstream y_matrix_stream;
  arma::mat y_matrix  = RcppDeepState_mat();
  y_matrix_stream.open("/home/akhila/fuzzer_packages/fuzzedpackages/UPG/inst/testfiles/sample_probit/inputs/y_matrix");
  y_matrix_stream << y_matrix;
  std::cout << "y_matrix values: "<< y_matrix << std::endl;
  y_matrix_stream.close();
  std::ofstream y_categ_stream;
  arma::mat y_categ  = RcppDeepState_mat();
  y_categ_stream.open("/home/akhila/fuzzer_packages/fuzzedpackages/UPG/inst/testfiles/sample_probit/inputs/y_categ");
  y_categ_stream << y_categ;
  std::cout << "y_categ values: "<< y_categ << std::endl;
  y_categ_stream.close();
  std::ofstream X_stream;
  arma::mat X  = RcppDeepState_mat();
  X_stream.open("/home/akhila/fuzzer_packages/fuzzedpackages/UPG/inst/testfiles/sample_probit/inputs/X");
  X_stream << X;
  std::cout << "X values: "<< X << std::endl;
  X_stream.close();
  std::ofstream beta_old_stream;
  arma::mat beta_old  = RcppDeepState_mat();
  beta_old_stream.open("/home/akhila/fuzzer_packages/fuzzedpackages/UPG/inst/testfiles/sample_probit/inputs/beta_old");
  beta_old_stream << beta_old;
  std::cout << "beta_old values: "<< beta_old << std::endl;
  beta_old_stream.close();
  IntegerVector nsave(1);
  nsave[0]  = RcppDeepState_int();
  qs::c_qsave(nsave,"/home/akhila/fuzzer_packages/fuzzedpackages/UPG/inst/testfiles/sample_probit/inputs/nsave.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "nsave values: "<< nsave << std::endl;
  IntegerVector nburn(1);
  nburn[0]  = RcppDeepState_int();
  qs::c_qsave(nburn,"/home/akhila/fuzzer_packages/fuzzedpackages/UPG/inst/testfiles/sample_probit/inputs/nburn.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "nburn values: "<< nburn << std::endl;
  NumericVector A0(1);
  A0[0]  = RcppDeepState_double();
  qs::c_qsave(A0,"/home/akhila/fuzzer_packages/fuzzedpackages/UPG/inst/testfiles/sample_probit/inputs/A0.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "A0 values: "<< A0 << std::endl;
  NumericVector d0(1);
  d0[0]  = RcppDeepState_double();
  qs::c_qsave(d0,"/home/akhila/fuzzer_packages/fuzzedpackages/UPG/inst/testfiles/sample_probit/inputs/d0.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "d0 values: "<< d0 << std::endl;
  NumericVector D0(1);
  D0[0]  = RcppDeepState_double();
  qs::c_qsave(D0,"/home/akhila/fuzzer_packages/fuzzedpackages/UPG/inst/testfiles/sample_probit/inputs/D0.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "D0 values: "<< D0 << std::endl;
  NumericVector G0(1);
  G0[0]  = RcppDeepState_double();
  qs::c_qsave(G0,"/home/akhila/fuzzer_packages/fuzzedpackages/UPG/inst/testfiles/sample_probit/inputs/G0.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "G0 values: "<< G0 << std::endl;
  IntegerVector BOOST(1);
  BOOST[0]  = RcppDeepState_int();
  qs::c_qsave(BOOST,"/home/akhila/fuzzer_packages/fuzzedpackages/UPG/inst/testfiles/sample_probit/inputs/BOOST.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "BOOST values: "<< BOOST << std::endl;
  IntegerVector verbose(1);
  verbose[0]  = RcppDeepState_int();
  qs::c_qsave(verbose,"/home/akhila/fuzzer_packages/fuzzedpackages/UPG/inst/testfiles/sample_probit/inputs/verbose.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "verbose values: "<< verbose << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    sample_probit(y_matrix,y_categ,X,beta_old,nsave[0],nburn[0],A0[0],d0[0],D0[0],G0[0],BOOST[0],verbose[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
