// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// Bpert_DeepState_TestHarness_generation.cpp and Bpert_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

arma::mat Bpert(int bsize, int tr_num);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  IntegerVector bsize(1);
  bsize[0]  = RcppDeepState_int();
  qs::c_qsave(bsize,"/home/akhila/fuzzer_packages/fuzzedpackages/carat/inst/testfiles/Bpert/inputs/bsize.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "bsize values: "<< bsize << std::endl;
  IntegerVector tr_num(1);
  tr_num[0]  = RcppDeepState_int();
  qs::c_qsave(tr_num,"/home/akhila/fuzzer_packages/fuzzedpackages/carat/inst/testfiles/Bpert/inputs/tr_num.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "tr_num values: "<< tr_num << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    Bpert(bsize[0],tr_num[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
