// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// scan_pg_onechr_DeepState_TestHarness_generation.cpp and scan_pg_onechr_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector scan_pg_onechr(const NumericVector& genoprobs, const NumericMatrix& pheno, const NumericMatrix& addcovar, const NumericMatrix& eigenvec, const NumericVector& weights, const double tol);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector genoprobs  = RcppDeepState_NumericVector();
  qs::c_qsave(genoprobs,"/home/akhila/fuzzer_packages/fuzzedpackages/qtl2/inst/testfiles/scan_pg_onechr/inputs/genoprobs.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "genoprobs values: "<< genoprobs << std::endl;
  NumericMatrix pheno  = RcppDeepState_NumericMatrix();
  qs::c_qsave(pheno,"/home/akhila/fuzzer_packages/fuzzedpackages/qtl2/inst/testfiles/scan_pg_onechr/inputs/pheno.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "pheno values: "<< pheno << std::endl;
  NumericMatrix addcovar  = RcppDeepState_NumericMatrix();
  qs::c_qsave(addcovar,"/home/akhila/fuzzer_packages/fuzzedpackages/qtl2/inst/testfiles/scan_pg_onechr/inputs/addcovar.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "addcovar values: "<< addcovar << std::endl;
  NumericMatrix eigenvec  = RcppDeepState_NumericMatrix();
  qs::c_qsave(eigenvec,"/home/akhila/fuzzer_packages/fuzzedpackages/qtl2/inst/testfiles/scan_pg_onechr/inputs/eigenvec.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "eigenvec values: "<< eigenvec << std::endl;
  NumericVector weights  = RcppDeepState_NumericVector();
  qs::c_qsave(weights,"/home/akhila/fuzzer_packages/fuzzedpackages/qtl2/inst/testfiles/scan_pg_onechr/inputs/weights.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "weights values: "<< weights << std::endl;
  NumericVector tol(1);
  tol[0]  = RcppDeepState_double();
  qs::c_qsave(tol,"/home/akhila/fuzzer_packages/fuzzedpackages/qtl2/inst/testfiles/scan_pg_onechr/inputs/tol.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "tol values: "<< tol << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    scan_pg_onechr(genoprobs,pheno,addcovar,eigenvec,weights,tol[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
