// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// mictools_null_DeepState_TestHarness_generation.cpp and mictools_null_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector mictools_null(NumericMatrix x, double alpha, double C, int nperm, int seed);

TEST(,){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericMatrix x  = RcppDeepState_NumericMatrix();
  std::string x_t = "/home/akhila/fuzzer_packages/fuzzedpackages/minerva/inst/testfiles/mictools_null/libFuzzer_mictools_null/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_x.qs";
  qs::c_qsave(x,x_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "x values: "<< x << std::endl;
  NumericVector alpha(1);
  alpha[0]  = RcppDeepState_double();
  std::string alpha_t = "/home/akhila/fuzzer_packages/fuzzedpackages/minerva/inst/testfiles/mictools_null/libFuzzer_mictools_null/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_alpha.qs";
  qs::c_qsave(alpha,alpha_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "alpha values: "<< alpha << std::endl;
  NumericVector C(1);
  C[0]  = RcppDeepState_double();
  std::string C_t = "/home/akhila/fuzzer_packages/fuzzedpackages/minerva/inst/testfiles/mictools_null/libFuzzer_mictools_null/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_C.qs";
  qs::c_qsave(C,C_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "C values: "<< C << std::endl;
  IntegerVector nperm(1);
  nperm[0]  = RcppDeepState_int();
  std::string nperm_t = "/home/akhila/fuzzer_packages/fuzzedpackages/minerva/inst/testfiles/mictools_null/libFuzzer_mictools_null/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_nperm.qs";
  qs::c_qsave(nperm,nperm_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "nperm values: "<< nperm << std::endl;
  IntegerVector seed(1);
  seed[0]  = RcppDeepState_int();
  std::string seed_t = "/home/akhila/fuzzer_packages/fuzzedpackages/minerva/inst/testfiles/mictools_null/libFuzzer_mictools_null/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_seed.qs";
  qs::c_qsave(seed,seed_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "seed values: "<< seed << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    mictools_null(x,alpha[0],C[0],nperm[0],seed[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
