// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// find_groups_cpp_DeepState_TestHarness_generation.cpp and find_groups_cpp_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericMatrix find_groups_cpp(NumericMatrix max_z_matrix);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericMatrix max_z_matrix  = RcppDeepState_NumericMatrix();
  qs::c_qsave(max_z_matrix,"/home/akhila/fuzzer_packages/fuzzedpackages/rayshader/inst/testfiles/find_groups_cpp/inputs/max_z_matrix.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "max_z_matrix values: "<< max_z_matrix << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    find_groups_cpp(max_z_matrix);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
