// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// comp_preds_DeepState_TestHarness_generation.cpp and comp_preds_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector comp_preds(IntegerVector& indx, int& node_nobs, IntegerVector& node_cols, NumericVector& bwts, NumericMatrix& dmat);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  IntegerVector indx  = RcppDeepState_IntegerVector();
  qs::c_qsave(indx,"/home/akhila/fuzzer_packages/fuzzedpackages/obliqueRSF/inst/testfiles/comp_preds/inputs/indx.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "indx values: "<< indx << std::endl;
  IntegerVector node_nobs(1);
  node_nobs[0]  = RcppDeepState_int();
  qs::c_qsave(node_nobs,"/home/akhila/fuzzer_packages/fuzzedpackages/obliqueRSF/inst/testfiles/comp_preds/inputs/node_nobs.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "node_nobs values: "<< node_nobs << std::endl;
  IntegerVector node_cols  = RcppDeepState_IntegerVector();
  qs::c_qsave(node_cols,"/home/akhila/fuzzer_packages/fuzzedpackages/obliqueRSF/inst/testfiles/comp_preds/inputs/node_cols.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "node_cols values: "<< node_cols << std::endl;
  NumericVector bwts  = RcppDeepState_NumericVector();
  qs::c_qsave(bwts,"/home/akhila/fuzzer_packages/fuzzedpackages/obliqueRSF/inst/testfiles/comp_preds/inputs/bwts.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "bwts values: "<< bwts << std::endl;
  NumericMatrix dmat  = RcppDeepState_NumericMatrix();
  qs::c_qsave(dmat,"/home/akhila/fuzzer_packages/fuzzedpackages/obliqueRSF/inst/testfiles/comp_preds/inputs/dmat.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "dmat values: "<< dmat << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    comp_preds(indx,node_nobs[0],node_cols,bwts,dmat);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
