// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// sttcp_ab_DeepState_TestHarness_generation.cpp and sttcp_ab_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector sttcp_ab(NumericVector a, NumericVector b, double start, double end, double dt, double tau_sep, double tau_max);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector a  = RcppDeepState_NumericVector();
  qs::c_qsave(a,"/home/akhila/fuzzer_packages/fuzzedpackages/meaRtools/inst/testfiles/sttcp_ab/inputs/a.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "a values: "<< a << std::endl;
  NumericVector b  = RcppDeepState_NumericVector();
  qs::c_qsave(b,"/home/akhila/fuzzer_packages/fuzzedpackages/meaRtools/inst/testfiles/sttcp_ab/inputs/b.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "b values: "<< b << std::endl;
  NumericVector start(1);
  start[0]  = RcppDeepState_double();
  qs::c_qsave(start,"/home/akhila/fuzzer_packages/fuzzedpackages/meaRtools/inst/testfiles/sttcp_ab/inputs/start.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "start values: "<< start << std::endl;
  NumericVector end(1);
  end[0]  = RcppDeepState_double();
  qs::c_qsave(end,"/home/akhila/fuzzer_packages/fuzzedpackages/meaRtools/inst/testfiles/sttcp_ab/inputs/end.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "end values: "<< end << std::endl;
  NumericVector dt(1);
  dt[0]  = RcppDeepState_double();
  qs::c_qsave(dt,"/home/akhila/fuzzer_packages/fuzzedpackages/meaRtools/inst/testfiles/sttcp_ab/inputs/dt.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "dt values: "<< dt << std::endl;
  NumericVector tau_sep(1);
  tau_sep[0]  = RcppDeepState_double();
  qs::c_qsave(tau_sep,"/home/akhila/fuzzer_packages/fuzzedpackages/meaRtools/inst/testfiles/sttcp_ab/inputs/tau_sep.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "tau_sep values: "<< tau_sep << std::endl;
  NumericVector tau_max(1);
  tau_max[0]  = RcppDeepState_double();
  qs::c_qsave(tau_max,"/home/akhila/fuzzer_packages/fuzzedpackages/meaRtools/inst/testfiles/sttcp_ab/inputs/tau_max.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "tau_max values: "<< tau_max << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    sttcp_ab(a,b,start[0],end[0],dt[0],tau_sep[0],tau_max[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
