// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// trps_DeepState_TestHarness_generation.cpp and trps_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

double trps(const NumericMatrix& m, NumericVector outcome, NumericVector rankweights);

TEST(,){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericMatrix m  = RcppDeepState_NumericMatrix();
  std::string m_t = "/home/akhila/fuzzer_packages/fuzzedpackages/socceR/inst/testfiles/trps/libFuzzer_trps/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_m.qs";
  qs::c_qsave(m,m_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "m values: "<< m << std::endl;
  NumericVector outcome  = RcppDeepState_NumericVector();
  std::string outcome_t = "/home/akhila/fuzzer_packages/fuzzedpackages/socceR/inst/testfiles/trps/libFuzzer_trps/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_outcome.qs";
  qs::c_qsave(outcome,outcome_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "outcome values: "<< outcome << std::endl;
  NumericVector rankweights  = RcppDeepState_NumericVector();
  std::string rankweights_t = "/home/akhila/fuzzer_packages/fuzzedpackages/socceR/inst/testfiles/trps/libFuzzer_trps/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_rankweights.qs";
  qs::c_qsave(rankweights,rankweights_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "rankweights values: "<< rankweights << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    trps(m,outcome,rankweights);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
