// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// similarityMatC_DeepState_TestHarness_generation.cpp and similarityMatC_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

List similarityMatC(const arma::mat& cc);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  std::ofstream cc_stream;
  arma::mat cc  = RcppDeepState_mat();
  cc_stream.open("/home/akhila/fuzzer_packages/fuzzedpackages/NPflow/inst/testfiles/similarityMatC/inputs/cc");
  cc_stream << cc;
  std::cout << "cc values: "<< cc << std::endl;
  cc_stream.close();
  std::cout << "input ends" << std::endl;
  try{
    similarityMatC(cc);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
