// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// mdmb_rcpp_oprobit_derivative_logthresh_chain_rule_DeepState_TestHarness_generation.cpp and mdmb_rcpp_oprobit_derivative_logthresh_chain_rule_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

Rcpp::NumericMatrix mdmb_rcpp_oprobit_derivative_logthresh_chain_rule(Rcpp::NumericVector thresh_der, Rcpp::NumericVector probs, Rcpp::NumericVector dens_upp, Rcpp::NumericVector dens_low, Rcpp::IntegerVector y, double eps, int y_value);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector thresh_der  = RcppDeepState_NumericVector();
  qs::c_qsave(thresh_der,"/home/akhila/fuzzer_packages/fuzzedpackages/mdmb/inst/testfiles/mdmb_rcpp_oprobit_derivative_logthresh_chain_rule/inputs/thresh_der.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "thresh_der values: "<< thresh_der << std::endl;
  NumericVector probs  = RcppDeepState_NumericVector();
  qs::c_qsave(probs,"/home/akhila/fuzzer_packages/fuzzedpackages/mdmb/inst/testfiles/mdmb_rcpp_oprobit_derivative_logthresh_chain_rule/inputs/probs.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "probs values: "<< probs << std::endl;
  NumericVector dens_upp  = RcppDeepState_NumericVector();
  qs::c_qsave(dens_upp,"/home/akhila/fuzzer_packages/fuzzedpackages/mdmb/inst/testfiles/mdmb_rcpp_oprobit_derivative_logthresh_chain_rule/inputs/dens_upp.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "dens_upp values: "<< dens_upp << std::endl;
  NumericVector dens_low  = RcppDeepState_NumericVector();
  qs::c_qsave(dens_low,"/home/akhila/fuzzer_packages/fuzzedpackages/mdmb/inst/testfiles/mdmb_rcpp_oprobit_derivative_logthresh_chain_rule/inputs/dens_low.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "dens_low values: "<< dens_low << std::endl;
  IntegerVector y  = RcppDeepState_IntegerVector();
  qs::c_qsave(y,"/home/akhila/fuzzer_packages/fuzzedpackages/mdmb/inst/testfiles/mdmb_rcpp_oprobit_derivative_logthresh_chain_rule/inputs/y.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "y values: "<< y << std::endl;
  NumericVector eps(1);
  eps[0]  = RcppDeepState_double();
  qs::c_qsave(eps,"/home/akhila/fuzzer_packages/fuzzedpackages/mdmb/inst/testfiles/mdmb_rcpp_oprobit_derivative_logthresh_chain_rule/inputs/eps.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "eps values: "<< eps << std::endl;
  IntegerVector y_value(1);
  y_value[0]  = RcppDeepState_int();
  qs::c_qsave(y_value,"/home/akhila/fuzzer_packages/fuzzedpackages/mdmb/inst/testfiles/mdmb_rcpp_oprobit_derivative_logthresh_chain_rule/inputs/y_value.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "y_value values: "<< y_value << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    mdmb_rcpp_oprobit_derivative_logthresh_chain_rule(thresh_der,probs,dens_upp,dens_low,y,eps[0],y_value[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
