// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// setmirtjml_threads_DeepState_TestHarness_generation.cpp and setmirtjml_threads_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

int setmirtjml_threads(int threads);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  IntegerVector threads(1);
  threads[0]  = RcppDeepState_int();
  qs::c_qsave(threads,"/home/akhila/fuzzer_packages/fuzzedpackages/mirtjml/inst/testfiles/setmirtjml_threads/inputs/threads.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "threads values: "<< threads << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    setmirtjml_threads(threads[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
