// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// wasserstein_distance_DeepState_TestHarness_generation.cpp and wasserstein_distance_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

double wasserstein_distance(const Rcpp::NumericMatrix& Diag1, const Rcpp::NumericMatrix& Diag2, int q, double internal_p, double delta, double initial_eps, double eps_factor);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericMatrix Diag1  = RcppDeepState_NumericMatrix();
  qs::c_qsave(Diag1,"/home/akhila/fuzzer_packages/fuzzedpackages/kernelTDA/inst/testfiles/wasserstein_distance/inputs/Diag1.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "Diag1 values: "<< Diag1 << std::endl;
  NumericMatrix Diag2  = RcppDeepState_NumericMatrix();
  qs::c_qsave(Diag2,"/home/akhila/fuzzer_packages/fuzzedpackages/kernelTDA/inst/testfiles/wasserstein_distance/inputs/Diag2.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "Diag2 values: "<< Diag2 << std::endl;
  IntegerVector q(1);
  q[0]  = RcppDeepState_int();
  qs::c_qsave(q,"/home/akhila/fuzzer_packages/fuzzedpackages/kernelTDA/inst/testfiles/wasserstein_distance/inputs/q.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "q values: "<< q << std::endl;
  NumericVector internal_p(1);
  internal_p[0]  = RcppDeepState_double();
  qs::c_qsave(internal_p,"/home/akhila/fuzzer_packages/fuzzedpackages/kernelTDA/inst/testfiles/wasserstein_distance/inputs/internal_p.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "internal_p values: "<< internal_p << std::endl;
  NumericVector delta(1);
  delta[0]  = RcppDeepState_double();
  qs::c_qsave(delta,"/home/akhila/fuzzer_packages/fuzzedpackages/kernelTDA/inst/testfiles/wasserstein_distance/inputs/delta.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "delta values: "<< delta << std::endl;
  NumericVector initial_eps(1);
  initial_eps[0]  = RcppDeepState_double();
  qs::c_qsave(initial_eps,"/home/akhila/fuzzer_packages/fuzzedpackages/kernelTDA/inst/testfiles/wasserstein_distance/inputs/initial_eps.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "initial_eps values: "<< initial_eps << std::endl;
  NumericVector eps_factor(1);
  eps_factor[0]  = RcppDeepState_double();
  qs::c_qsave(eps_factor,"/home/akhila/fuzzer_packages/fuzzedpackages/kernelTDA/inst/testfiles/wasserstein_distance/inputs/eps_factor.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "eps_factor values: "<< eps_factor << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    wasserstein_distance(Diag1,Diag2,q[0],internal_p[0],delta[0],initial_eps[0],eps_factor[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
