// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// rooted_shape_to_edge_DeepState_TestHarness_generation.cpp and rooted_shape_to_edge_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

IntegerMatrix rooted_shape_to_edge(NumericVector shape, IntegerVector nTip);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector shape  = RcppDeepState_NumericVector();
  qs::c_qsave(shape,"/home/akhila/fuzzer_packages/fuzzedpackages/TreeTools/inst/testfiles/rooted_shape_to_edge/inputs/shape.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "shape values: "<< shape << std::endl;
  IntegerVector nTip  = RcppDeepState_IntegerVector();
  qs::c_qsave(nTip,"/home/akhila/fuzzer_packages/fuzzedpackages/TreeTools/inst/testfiles/rooted_shape_to_edge/inputs/nTip.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "nTip values: "<< nTip << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    rooted_shape_to_edge(shape,nTip);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
