// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// mkpix2xyC_DeepState_TestHarness_generation.cpp and mkpix2xyC_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

IntegerMatrix mkpix2xyC(int nside);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  IntegerVector nside(1);
  nside[0]  = RcppDeepState_int();
  qs::c_qsave(nside,"/home/akhila/fuzzer_packages/fuzzedpackages/rcosmo/inst/testfiles/mkpix2xyC/inputs/nside.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "nside values: "<< nside << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    mkpix2xyC(nside[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
