// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// SchurC_DeepState_TestHarness_generation.cpp and SchurC_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

SEXP SchurC(const arma::mat Ibb, const arma::mat Iaa, const arma::mat Iba);

TEST(,){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  std::ofstream Ibb_stream;
  arma::mat Ibb  = RcppDeepState_mat();
  Ibb_stream.open("/home/akhila/fuzzer_packages/fuzzedpackages/SurrogateRegression/inst/testfiles/SchurC/inputs/Ibb");
  Ibb_stream << Ibb;
  std::cout << "Ibb values: "<< Ibb << std::endl;
  Ibb_stream.close();
  std::ofstream Iaa_stream;
  arma::mat Iaa  = RcppDeepState_mat();
  Iaa_stream.open("/home/akhila/fuzzer_packages/fuzzedpackages/SurrogateRegression/inst/testfiles/SchurC/inputs/Iaa");
  Iaa_stream << Iaa;
  std::cout << "Iaa values: "<< Iaa << std::endl;
  Iaa_stream.close();
  std::ofstream Iba_stream;
  arma::mat Iba  = RcppDeepState_mat();
  Iba_stream.open("/home/akhila/fuzzer_packages/fuzzedpackages/SurrogateRegression/inst/testfiles/SchurC/inputs/Iba");
  Iba_stream << Iba;
  std::cout << "Iba values: "<< Iba << std::endl;
  Iba_stream.close();
  std::cout << "input ends" << std::endl;
  try{
    SchurC(Ibb,Iaa,Iba);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
