// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// tdnorm_DeepState_TestHarness_generation.cpp and tdnorm_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector tdnorm(NumericVector x, double mi, double ma);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector x  = RcppDeepState_NumericVector();
  qs::c_qsave(x,"/home/akhila/fuzzer_packages/fuzzedpackages/MSEtool/inst/testfiles/tdnorm/inputs/x.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "x values: "<< x << std::endl;
  NumericVector mi(1);
  mi[0]  = RcppDeepState_double();
  qs::c_qsave(mi,"/home/akhila/fuzzer_packages/fuzzedpackages/MSEtool/inst/testfiles/tdnorm/inputs/mi.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "mi values: "<< mi << std::endl;
  NumericVector ma(1);
  ma[0]  = RcppDeepState_double();
  qs::c_qsave(ma,"/home/akhila/fuzzer_packages/fuzzedpackages/MSEtool/inst/testfiles/tdnorm/inputs/ma.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "ma values: "<< ma << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    tdnorm(x,mi[0],ma[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
