// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// sum_in_temp_DeepState_TestHarness_generation.cpp and sum_in_temp_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector& sum_in_temp(const NumericVector& x, const NumericVector& y, NumericVector& tmp_vec);

TEST(,){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericVector x  = RcppDeepState_NumericVector();
  std::string x_t = "/home/akhila/fuzzer_packages/fuzzedpackages/bigutilsr/inst/testfiles/sum_in_temp/libFuzzer_sum_in_temp/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_x.qs";
  qs::c_qsave(x,x_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "x values: "<< x << std::endl;
  NumericVector y  = RcppDeepState_NumericVector();
  std::string y_t = "/home/akhila/fuzzer_packages/fuzzedpackages/bigutilsr/inst/testfiles/sum_in_temp/libFuzzer_sum_in_temp/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_y.qs";
  qs::c_qsave(y,y_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "y values: "<< y << std::endl;
  NumericVector tmp_vec  = RcppDeepState_NumericVector();
  std::string tmp_vec_t = "/home/akhila/fuzzer_packages/fuzzedpackages/bigutilsr/inst/testfiles/sum_in_temp/libFuzzer_sum_in_temp/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_tmp_vec.qs";
  qs::c_qsave(tmp_vec,tmp_vec_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "tmp_vec values: "<< tmp_vec << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    sum_in_temp(x,y,tmp_vec);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
