// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// rowSumsSq_DeepState_TestHarness_generation.cpp and rowSumsSq_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector rowSumsSq(const NumericMatrix& source);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericMatrix source  = RcppDeepState_NumericMatrix();
  qs::c_qsave(source,"/home/akhila/fuzzer_packages/fuzzedpackages/bigutilsr/inst/testfiles/rowSumsSq/inputs/source.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "source values: "<< source << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    rowSumsSq(source);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
