// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// distanceToPeakCpp_DeepState_TestHarness_generation.cpp and distanceToPeakCpp_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector distanceToPeakCpp(NumericVector distance, NumericVector rho);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector distance  = RcppDeepState_NumericVector();
  qs::c_qsave(distance,"/home/akhila/fuzzer_packages/fuzzedpackages/densityClust/inst/testfiles/distanceToPeakCpp/inputs/distance.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "distance values: "<< distance << std::endl;
  NumericVector rho  = RcppDeepState_NumericVector();
  qs::c_qsave(rho,"/home/akhila/fuzzer_packages/fuzzedpackages/densityClust/inst/testfiles/distanceToPeakCpp/inputs/rho.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "rho values: "<< rho << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    distanceToPeakCpp(distance,rho);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
