// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// CTT_In_DeepState_TestHarness_generation.cpp and CTT_In_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

double CTT_In(arma::mat data);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  std::ofstream data_stream;
  arma::mat data  = RcppDeepState_mat();
  data_stream.open("/home/akhila/fuzzer_packages/fuzzedpackages/carat/inst/testfiles/CTT_In/inputs/data");
  data_stream << data;
  std::cout << "data values: "<< data << std::endl;
  data_stream.close();
  std::cout << "input ends" << std::endl;
  try{
    CTT_In(data);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
