// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// AUCijFun_DeepState_TestHarness_generation.cpp and AUCijFun_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericMatrix AUCijFun(NumericVector riskCase, NumericVector riskControl);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector riskCase  = RcppDeepState_NumericVector();
  qs::c_qsave(riskCase,"/home/akhila/fuzzer_packages/fuzzedpackages/riskRegression/inst/testfiles/AUCijFun/inputs/riskCase.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "riskCase values: "<< riskCase << std::endl;
  NumericVector riskControl  = RcppDeepState_NumericVector();
  qs::c_qsave(riskControl,"/home/akhila/fuzzer_packages/fuzzedpackages/riskRegression/inst/testfiles/AUCijFun/inputs/riskControl.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "riskControl values: "<< riskControl << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    AUCijFun(riskCase,riskControl);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
