// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// scaleTau2_vector_rcpp_DeepState_TestHarness_generation.cpp and scaleTau2_vector_rcpp_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector scaleTau2_vector_rcpp(const NumericVector& x, NumericVector& tmp_dev, NumericVector& tmp_med);

TEST(,){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericVector x  = RcppDeepState_NumericVector();
  std::string x_t = "/home/akhila/fuzzer_packages/fuzzedpackages/bigutilsr/inst/testfiles/scaleTau2_vector_rcpp/libFuzzer_scaleTau2_vector_rcpp/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_x.qs";
  qs::c_qsave(x,x_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "x values: "<< x << std::endl;
  NumericVector tmp_dev  = RcppDeepState_NumericVector();
  std::string tmp_dev_t = "/home/akhila/fuzzer_packages/fuzzedpackages/bigutilsr/inst/testfiles/scaleTau2_vector_rcpp/libFuzzer_scaleTau2_vector_rcpp/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_tmp_dev.qs";
  qs::c_qsave(tmp_dev,tmp_dev_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "tmp_dev values: "<< tmp_dev << std::endl;
  NumericVector tmp_med  = RcppDeepState_NumericVector();
  std::string tmp_med_t = "/home/akhila/fuzzer_packages/fuzzedpackages/bigutilsr/inst/testfiles/scaleTau2_vector_rcpp/libFuzzer_scaleTau2_vector_rcpp/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_tmp_med.qs";
  qs::c_qsave(tmp_med,tmp_med_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "tmp_med values: "<< tmp_med << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    scaleTau2_vector_rcpp(x,tmp_dev,tmp_med);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
