// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// AdjBCD_RT_In_DeepState_TestHarness_generation.cpp and AdjBCD_RT_In_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

double AdjBCD_RT_In(arma::mat data, double Reps, double a);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  std::ofstream data_stream;
  arma::mat data  = RcppDeepState_mat();
  data_stream.open("/home/akhila/fuzzer_packages/fuzzedpackages/carat/inst/testfiles/AdjBCD_RT_In/inputs/data");
  data_stream << data;
  std::cout << "data values: "<< data << std::endl;
  data_stream.close();
  NumericVector Reps(1);
  Reps[0]  = RcppDeepState_double();
  qs::c_qsave(Reps,"/home/akhila/fuzzer_packages/fuzzedpackages/carat/inst/testfiles/AdjBCD_RT_In/inputs/Reps.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "Reps values: "<< Reps << std::endl;
  NumericVector a(1);
  a[0]  = RcppDeepState_double();
  qs::c_qsave(a,"/home/akhila/fuzzer_packages/fuzzedpackages/carat/inst/testfiles/AdjBCD_RT_In/inputs/a.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "a values: "<< a << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    AdjBCD_RT_In(data,Reps[0],a[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
