// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// generateDataFrame_one_rcpp_DeepState_TestHarness_generation.cpp and generateDataFrame_one_rcpp_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

DataFrame generateDataFrame_one_rcpp(NumericMatrix matKernel2, CharacterVector functionNames);

TEST(,){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericMatrix matKernel2  = RcppDeepState_NumericMatrix();
  std::string matKernel2_t = "/home/akhila/fuzzer_packages/fuzzedpackages/SimilaR/inst/testfiles/generateDataFrame_one_rcpp/libFuzzer_generateDataFrame_one_rcpp/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_matKernel2.qs";
  qs::c_qsave(matKernel2,matKernel2_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "matKernel2 values: "<< matKernel2 << std::endl;
  CharacterVector functionNames  = RcppDeepState_CharacterVector();
  std::string functionNames_t = "/home/akhila/fuzzer_packages/fuzzedpackages/SimilaR/inst/testfiles/generateDataFrame_one_rcpp/libFuzzer_generateDataFrame_one_rcpp/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_functionNames.qs";
  qs::c_qsave(functionNames,functionNames_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "functionNames values: "<< functionNames << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    generateDataFrame_one_rcpp(matKernel2,functionNames);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
