// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// vecpower_DeepState_TestHarness_generation.cpp and vecpower_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

Rcpp::NumericVector vecpower(const Rcpp::NumericVector& base, const Rcpp::NumericVector& exp);

TEST(,){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericVector base  = RcppDeepState_NumericVector();
  std::string base_t = "/home/akhila/fuzzer_packages/fuzzedpackages/rust/inst/testfiles/vecpower/libFuzzer_vecpower/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_base.qs";
  qs::c_qsave(base,base_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "base values: "<< base << std::endl;
  NumericVector exp  = RcppDeepState_NumericVector();
  std::string exp_t = "/home/akhila/fuzzer_packages/fuzzedpackages/rust/inst/testfiles/vecpower/libFuzzer_vecpower/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_exp.qs";
  qs::c_qsave(exp,exp_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "exp values: "<< exp << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    vecpower(base,exp);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
