// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// SIGMA_DeepState_TestHarness_generation.cpp and SIGMA_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

arma::mat SIGMA(double Phi, int TempCorInd, arma::mat const& TimeDist, int Nu);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector Phi(1);
  Phi[0]  = RcppDeepState_double();
  qs::c_qsave(Phi,"/home/akhila/fuzzer_packages/fuzzedpackages/womblR/inst/testfiles/SIGMA/inputs/Phi.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "Phi values: "<< Phi << std::endl;
  IntegerVector TempCorInd(1);
  TempCorInd[0]  = RcppDeepState_int();
  qs::c_qsave(TempCorInd,"/home/akhila/fuzzer_packages/fuzzedpackages/womblR/inst/testfiles/SIGMA/inputs/TempCorInd.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "TempCorInd values: "<< TempCorInd << std::endl;
  std::ofstream TimeDist_stream;
  arma::mat TimeDist  = RcppDeepState_mat();
  TimeDist_stream.open("/home/akhila/fuzzer_packages/fuzzedpackages/womblR/inst/testfiles/SIGMA/inputs/TimeDist");
  TimeDist_stream << TimeDist;
  std::cout << "TimeDist values: "<< TimeDist << std::endl;
  TimeDist_stream.close();
  IntegerVector Nu(1);
  Nu[0]  = RcppDeepState_int();
  qs::c_qsave(Nu,"/home/akhila/fuzzer_packages/fuzzedpackages/womblR/inst/testfiles/SIGMA/inputs/Nu.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "Nu values: "<< Nu << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    SIGMA(Phi[0],TempCorInd[0],TimeDist,Nu[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
