// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// mdmb_rcpp_oprobit_derivative_ypred_DeepState_TestHarness_generation.cpp and mdmb_rcpp_oprobit_derivative_ypred_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

Rcpp::List mdmb_rcpp_oprobit_derivative_ypred(Rcpp::NumericVector ypred, Rcpp::NumericVector thresh_low, Rcpp::NumericVector thresh_upp, Rcpp::NumericVector y);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector ypred  = RcppDeepState_NumericVector();
  qs::c_qsave(ypred,"/home/akhila/fuzzer_packages/fuzzedpackages/mdmb/inst/testfiles/mdmb_rcpp_oprobit_derivative_ypred/inputs/ypred.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "ypred values: "<< ypred << std::endl;
  NumericVector thresh_low  = RcppDeepState_NumericVector();
  qs::c_qsave(thresh_low,"/home/akhila/fuzzer_packages/fuzzedpackages/mdmb/inst/testfiles/mdmb_rcpp_oprobit_derivative_ypred/inputs/thresh_low.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "thresh_low values: "<< thresh_low << std::endl;
  NumericVector thresh_upp  = RcppDeepState_NumericVector();
  qs::c_qsave(thresh_upp,"/home/akhila/fuzzer_packages/fuzzedpackages/mdmb/inst/testfiles/mdmb_rcpp_oprobit_derivative_ypred/inputs/thresh_upp.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "thresh_upp values: "<< thresh_upp << std::endl;
  NumericVector y  = RcppDeepState_NumericVector();
  qs::c_qsave(y,"/home/akhila/fuzzer_packages/fuzzedpackages/mdmb/inst/testfiles/mdmb_rcpp_oprobit_derivative_ypred/inputs/y.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "y values: "<< y << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    mdmb_rcpp_oprobit_derivative_ypred(ypred,thresh_low,thresh_upp,y);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
