// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// Rcpp_COMP_Z_DeepState_TestHarness_generation.cpp and Rcpp_COMP_Z_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

SEXP Rcpp_COMP_Z(int moment, double nu, double lambda, int maxn);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  IntegerVector moment(1);
  moment[0]  = RcppDeepState_int();
  qs::c_qsave(moment,"/home/akhila/fuzzer_packages/fuzzedpackages/spaMM/inst/testfiles/Rcpp_COMP_Z/inputs/moment.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "moment values: "<< moment << std::endl;
  NumericVector nu(1);
  nu[0]  = RcppDeepState_double();
  qs::c_qsave(nu,"/home/akhila/fuzzer_packages/fuzzedpackages/spaMM/inst/testfiles/Rcpp_COMP_Z/inputs/nu.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "nu values: "<< nu << std::endl;
  NumericVector lambda(1);
  lambda[0]  = RcppDeepState_double();
  qs::c_qsave(lambda,"/home/akhila/fuzzer_packages/fuzzedpackages/spaMM/inst/testfiles/Rcpp_COMP_Z/inputs/lambda.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "lambda values: "<< lambda << std::endl;
  IntegerVector maxn(1);
  maxn[0]  = RcppDeepState_int();
  qs::c_qsave(maxn,"/home/akhila/fuzzer_packages/fuzzedpackages/spaMM/inst/testfiles/Rcpp_COMP_Z/inputs/maxn.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "maxn values: "<< maxn << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    Rcpp_COMP_Z(moment[0],nu[0],lambda[0],maxn[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
