// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// logloss_DeepState_TestHarness_generation.cpp and logloss_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

double logloss(const NumericMatrix& m, NumericVector outcome, NumericVector rankweights);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericMatrix m  = RcppDeepState_NumericMatrix();
  qs::c_qsave(m,"/home/akhila/fuzzer_packages/fuzzedpackages/socceR/inst/testfiles/logloss/inputs/m.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "m values: "<< m << std::endl;
  NumericVector outcome  = RcppDeepState_NumericVector();
  qs::c_qsave(outcome,"/home/akhila/fuzzer_packages/fuzzedpackages/socceR/inst/testfiles/logloss/inputs/outcome.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "outcome values: "<< outcome << std::endl;
  NumericVector rankweights  = RcppDeepState_NumericVector();
  qs::c_qsave(rankweights,"/home/akhila/fuzzer_packages/fuzzedpackages/socceR/inst/testfiles/logloss/inputs/rankweights.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "rankweights values: "<< rankweights << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    logloss(m,outcome,rankweights);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
