// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// smallest_dist_rho_order_coords_DeepState_TestHarness_generation.cpp and smallest_dist_rho_order_coords_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

List smallest_dist_rho_order_coords(NumericVector ordered_rho, NumericVector ordered_coords);

TEST(,){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericVector ordered_rho  = RcppDeepState_NumericVector();
  std::string ordered_rho_t = "/home/akhila/fuzzer_packages/fuzzedpackages/densityClust/inst/testfiles/smallest_dist_rho_order_coords/libFuzzer_smallest_dist_rho_order_coords/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_ordered_rho.qs";
  qs::c_qsave(ordered_rho,ordered_rho_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "ordered_rho values: "<< ordered_rho << std::endl;
  NumericVector ordered_coords  = RcppDeepState_NumericVector();
  std::string ordered_coords_t = "/home/akhila/fuzzer_packages/fuzzedpackages/densityClust/inst/testfiles/smallest_dist_rho_order_coords/libFuzzer_smallest_dist_rho_order_coords/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_ordered_coords.qs";
  qs::c_qsave(ordered_coords,ordered_coords_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "ordered_coords values: "<< ordered_coords << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    smallest_dist_rho_order_coords(ordered_rho,ordered_coords);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
