// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// scan_pg_onechr_intcovar_highmem_DeepState_TestHarness_generation.cpp and scan_pg_onechr_intcovar_highmem_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector scan_pg_onechr_intcovar_highmem(const NumericVector& genoprobs, const NumericMatrix& pheno, const NumericMatrix& addcovar, const NumericMatrix& intcovar, const NumericMatrix& eigenvec, const NumericVector& weights, const double tol);

TEST(,){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericVector genoprobs  = RcppDeepState_NumericVector();
  std::string genoprobs_t = "/home/akhila/fuzzer_packages/fuzzedpackages/qtl2/inst/testfiles/scan_pg_onechr_intcovar_highmem/libFuzzer_scan_pg_onechr_intcovar_highmem/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_genoprobs.qs";
  qs::c_qsave(genoprobs,genoprobs_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "genoprobs values: "<< genoprobs << std::endl;
  NumericMatrix pheno  = RcppDeepState_NumericMatrix();
  std::string pheno_t = "/home/akhila/fuzzer_packages/fuzzedpackages/qtl2/inst/testfiles/scan_pg_onechr_intcovar_highmem/libFuzzer_scan_pg_onechr_intcovar_highmem/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_pheno.qs";
  qs::c_qsave(pheno,pheno_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "pheno values: "<< pheno << std::endl;
  NumericMatrix addcovar  = RcppDeepState_NumericMatrix();
  std::string addcovar_t = "/home/akhila/fuzzer_packages/fuzzedpackages/qtl2/inst/testfiles/scan_pg_onechr_intcovar_highmem/libFuzzer_scan_pg_onechr_intcovar_highmem/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_addcovar.qs";
  qs::c_qsave(addcovar,addcovar_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "addcovar values: "<< addcovar << std::endl;
  NumericMatrix intcovar  = RcppDeepState_NumericMatrix();
  std::string intcovar_t = "/home/akhila/fuzzer_packages/fuzzedpackages/qtl2/inst/testfiles/scan_pg_onechr_intcovar_highmem/libFuzzer_scan_pg_onechr_intcovar_highmem/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_intcovar.qs";
  qs::c_qsave(intcovar,intcovar_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "intcovar values: "<< intcovar << std::endl;
  NumericMatrix eigenvec  = RcppDeepState_NumericMatrix();
  std::string eigenvec_t = "/home/akhila/fuzzer_packages/fuzzedpackages/qtl2/inst/testfiles/scan_pg_onechr_intcovar_highmem/libFuzzer_scan_pg_onechr_intcovar_highmem/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_eigenvec.qs";
  qs::c_qsave(eigenvec,eigenvec_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "eigenvec values: "<< eigenvec << std::endl;
  NumericVector weights  = RcppDeepState_NumericVector();
  std::string weights_t = "/home/akhila/fuzzer_packages/fuzzedpackages/qtl2/inst/testfiles/scan_pg_onechr_intcovar_highmem/libFuzzer_scan_pg_onechr_intcovar_highmem/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_weights.qs";
  qs::c_qsave(weights,weights_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "weights values: "<< weights << std::endl;
  NumericVector tol(1);
  tol[0]  = RcppDeepState_double();
  std::string tol_t = "/home/akhila/fuzzer_packages/fuzzedpackages/qtl2/inst/testfiles/scan_pg_onechr_intcovar_highmem/libFuzzer_scan_pg_onechr_intcovar_highmem/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_tol.qs";
  qs::c_qsave(tol,tol_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "tol values: "<< tol << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    scan_pg_onechr_intcovar_highmem(genoprobs,pheno,addcovar,intcovar,eigenvec,weights,tol[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
