// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// check_gompertz_DeepState_TestHarness_generation.cpp and check_gompertz_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

Rcpp::LogicalVector check_gompertz(const Rcpp::NumericVector& shape, const Rcpp::NumericVector& rate);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector shape  = RcppDeepState_NumericVector();
  qs::c_qsave(shape,"/home/akhila/fuzzer_packages/fuzzedpackages/flexsurv/inst/testfiles/check_gompertz/inputs/shape.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "shape values: "<< shape << std::endl;
  NumericVector rate  = RcppDeepState_NumericVector();
  qs::c_qsave(rate,"/home/akhila/fuzzer_packages/fuzzedpackages/flexsurv/inst/testfiles/check_gompertz/inputs/rate.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "rate values: "<< rate << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    check_gompertz(shape,rate);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
