// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// movfit_Rcpp_DeepState_TestHarness_generation.cpp and movfit_Rcpp_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

double movfit_Rcpp(NumericVector par, double prb, double frac);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector par  = RcppDeepState_NumericVector();
  qs::c_qsave(par,"/home/akhila/fuzzer_packages/fuzzedpackages/MSEtool/inst/testfiles/movfit_Rcpp/inputs/par.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "par values: "<< par << std::endl;
  NumericVector prb(1);
  prb[0]  = RcppDeepState_double();
  qs::c_qsave(prb,"/home/akhila/fuzzer_packages/fuzzedpackages/MSEtool/inst/testfiles/movfit_Rcpp/inputs/prb.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "prb values: "<< prb << std::endl;
  NumericVector frac(1);
  frac[0]  = RcppDeepState_double();
  qs::c_qsave(frac,"/home/akhila/fuzzer_packages/fuzzedpackages/MSEtool/inst/testfiles/movfit_Rcpp/inputs/frac.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "frac values: "<< frac << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    movfit_Rcpp(par,prb[0],frac[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
