// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// rowSdsArma_DeepState_TestHarness_generation.cpp and rowSdsArma_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

arma::colvec rowSdsArma(const arma::mat& X, const int norm_type);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  std::ofstream X_stream;
  arma::mat X  = RcppDeepState_mat();
  X_stream.open("/home/akhila/fuzzer_packages/fuzzedpackages/GMCM/inst/testfiles/rowSdsArma/inputs/X");
  X_stream << X;
  std::cout << "X values: "<< X << std::endl;
  X_stream.close();
  IntegerVector norm_type(1);
  norm_type[0]  = RcppDeepState_int();
  qs::c_qsave(norm_type,"/home/akhila/fuzzer_packages/fuzzedpackages/GMCM/inst/testfiles/rowSdsArma/inputs/norm_type.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "norm_type values: "<< norm_type << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    rowSdsArma(X,norm_type[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
