// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// cvfolds_DeepState_TestHarness_generation.cpp and cvfolds_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

arma::vec cvfolds(double nfolds, double nrow);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector nfolds(1);
  nfolds[0]  = RcppDeepState_double();
  qs::c_qsave(nfolds,"/home/akhila/fuzzer_packages/fuzzedpackages/midasml/inst/testfiles/cvfolds/inputs/nfolds.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "nfolds values: "<< nfolds << std::endl;
  NumericVector nrow(1);
  nrow[0]  = RcppDeepState_double();
  qs::c_qsave(nrow,"/home/akhila/fuzzer_packages/fuzzedpackages/midasml/inst/testfiles/cvfolds/inputs/nrow.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "nrow values: "<< nrow << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    cvfolds(nfolds[0],nrow[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
