// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// logZ_c_DeepState_TestHarness_generation.cpp and logZ_c_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector logZ_c(NumericVector log_lambda, NumericVector nu, int summax);

TEST(,){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericVector log_lambda  = RcppDeepState_NumericVector();
  std::string log_lambda_t = "/home/akhila/fuzzer_packages/fuzzedpackages/mpcmp/inst/testfiles/logZ_c/libFuzzer_logZ_c/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_log_lambda.qs";
  qs::c_qsave(log_lambda,log_lambda_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "log_lambda values: "<< log_lambda << std::endl;
  NumericVector nu  = RcppDeepState_NumericVector();
  std::string nu_t = "/home/akhila/fuzzer_packages/fuzzedpackages/mpcmp/inst/testfiles/logZ_c/libFuzzer_logZ_c/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_nu.qs";
  qs::c_qsave(nu,nu_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "nu values: "<< nu << std::endl;
  IntegerVector summax(1);
  summax[0]  = RcppDeepState_int();
  std::string summax_t = "/home/akhila/fuzzer_packages/fuzzedpackages/mpcmp/inst/testfiles/logZ_c/libFuzzer_logZ_c/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_summax.qs";
  qs::c_qsave(summax,summax_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "summax values: "<< summax << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    logZ_c(log_lambda,nu,summax[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
