// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// revert_dist_list_cpp_DeepState_TestHarness_generation.cpp and revert_dist_list_cpp_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

List revert_dist_list_cpp(int n_t, int n_c, NumericVector startn, NumericVector endn, NumericVector d);

TEST(,){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  IntegerVector n_t(1);
  n_t[0]  = RcppDeepState_int();
  std::string n_t_t = "/home/akhila/fuzzer_packages/fuzzedpackages/match2C/inst/testfiles/revert_dist_list_cpp/libFuzzer_revert_dist_list_cpp/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_n_t.qs";
  qs::c_qsave(n_t,n_t_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "n_t values: "<< n_t << std::endl;
  IntegerVector n_c(1);
  n_c[0]  = RcppDeepState_int();
  std::string n_c_t = "/home/akhila/fuzzer_packages/fuzzedpackages/match2C/inst/testfiles/revert_dist_list_cpp/libFuzzer_revert_dist_list_cpp/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_n_c.qs";
  qs::c_qsave(n_c,n_c_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "n_c values: "<< n_c << std::endl;
  NumericVector startn  = RcppDeepState_NumericVector();
  std::string startn_t = "/home/akhila/fuzzer_packages/fuzzedpackages/match2C/inst/testfiles/revert_dist_list_cpp/libFuzzer_revert_dist_list_cpp/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_startn.qs";
  qs::c_qsave(startn,startn_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "startn values: "<< startn << std::endl;
  NumericVector endn  = RcppDeepState_NumericVector();
  std::string endn_t = "/home/akhila/fuzzer_packages/fuzzedpackages/match2C/inst/testfiles/revert_dist_list_cpp/libFuzzer_revert_dist_list_cpp/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_endn.qs";
  qs::c_qsave(endn,endn_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "endn values: "<< endn << std::endl;
  NumericVector d  = RcppDeepState_NumericVector();
  std::string d_t = "/home/akhila/fuzzer_packages/fuzzedpackages/match2C/inst/testfiles/revert_dist_list_cpp/libFuzzer_revert_dist_list_cpp/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_d.qs";
  qs::c_qsave(d,d_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "d values: "<< d << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    revert_dist_list_cpp(n_t[0],n_c[0],startn,endn,d);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
