// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// CheckFinite_DeepState_TestHarness_generation.cpp and CheckFinite_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

void CheckFinite(Rcpp::NumericMatrix matPtr);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericMatrix matPtr  = RcppDeepState_NumericMatrix();
  qs::c_qsave(matPtr,"/home/akhila/fuzzer_packages/fuzzedpackages/NetRep/inst/testfiles/CheckFinite/inputs/matPtr.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "matPtr values: "<< matPtr << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    CheckFinite(matPtr);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
