// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// unvectorize_DeepState_TestHarness_generation.cpp and unvectorize_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericMatrix unvectorize(const NumericVector& vect);

TEST(,){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericVector vect  = RcppDeepState_NumericVector();
  std::string vect_t = "/home/akhila/fuzzer_packages/fuzzedpackages/TestCor/inst/testfiles/unvectorize/libFuzzer_unvectorize/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_vect.qs";
  qs::c_qsave(vect,vect_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "vect values: "<< vect << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    unvectorize(vect);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
