// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// R_bayes_int_plain_DeepState_TestHarness_generation.cpp and R_bayes_int_plain_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

IntegerVector R_bayes_int_plain(const NumericVector& lod, const NumericVector& pos, const double prob);

TEST(,){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericVector lod  = RcppDeepState_NumericVector();
  std::string lod_t = "/home/akhila/fuzzer_packages/fuzzedpackages/qtl2/inst/testfiles/R_bayes_int_plain/libFuzzer_R_bayes_int_plain/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_lod.qs";
  qs::c_qsave(lod,lod_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "lod values: "<< lod << std::endl;
  NumericVector pos  = RcppDeepState_NumericVector();
  std::string pos_t = "/home/akhila/fuzzer_packages/fuzzedpackages/qtl2/inst/testfiles/R_bayes_int_plain/libFuzzer_R_bayes_int_plain/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_pos.qs";
  qs::c_qsave(pos,pos_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "pos values: "<< pos << std::endl;
  NumericVector prob(1);
  prob[0]  = RcppDeepState_double();
  std::string prob_t = "/home/akhila/fuzzer_packages/fuzzedpackages/qtl2/inst/testfiles/R_bayes_int_plain/libFuzzer_R_bayes_int_plain/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_prob.qs";
  qs::c_qsave(prob,prob_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "prob values: "<< prob << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    R_bayes_int_plain(lod,pos,prob[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
