// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// invert_sdp_DeepState_TestHarness_generation.cpp and invert_sdp_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

IntegerMatrix invert_sdp(const IntegerVector& sdp, const int n_str);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  IntegerVector sdp  = RcppDeepState_IntegerVector();
  qs::c_qsave(sdp,"/home/akhila/fuzzer_packages/fuzzedpackages/qtl2/inst/testfiles/invert_sdp/inputs/sdp.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "sdp values: "<< sdp << std::endl;
  IntegerVector n_str(1);
  n_str[0]  = RcppDeepState_int();
  qs::c_qsave(n_str,"/home/akhila/fuzzer_packages/fuzzedpackages/qtl2/inst/testfiles/invert_sdp/inputs/n_str.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "n_str values: "<< n_str << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    invert_sdp(sdp,n_str[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
