// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// dvm_rcpp_DeepState_TestHarness_generation.cpp and dvm_rcpp_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

arma::colvec dvm_rcpp(NumericVector x, double mu, double kappa);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector x  = RcppDeepState_NumericVector();
  qs::c_qsave(x,"/home/akhila/fuzzer_packages/fuzzedpackages/moveHMM/inst/testfiles/dvm_rcpp/inputs/x.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "x values: "<< x << std::endl;
  NumericVector mu(1);
  mu[0]  = RcppDeepState_double();
  qs::c_qsave(mu,"/home/akhila/fuzzer_packages/fuzzedpackages/moveHMM/inst/testfiles/dvm_rcpp/inputs/mu.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "mu values: "<< mu << std::endl;
  NumericVector kappa(1);
  kappa[0]  = RcppDeepState_double();
  qs::c_qsave(kappa,"/home/akhila/fuzzer_packages/fuzzedpackages/moveHMM/inst/testfiles/dvm_rcpp/inputs/kappa.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "kappa values: "<< kappa << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    dvm_rcpp(x,mu[0],kappa[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
