// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// subsample_DeepState_TestHarness_generation.cpp and subsample_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

arma::mat subsample(arma::mat& circle, int size);

TEST(,){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  std::ofstream circle_stream;
  arma::mat circle  = RcppDeepState_mat();
  circle_stream.open("/home/akhila/fuzzer_packages/fuzzedpackages/rayshader/inst/testfiles/subsample/inputs/circle");
  circle_stream << circle;
  std::cout << "circle values: "<< circle << std::endl;
  circle_stream.close();
  IntegerVector size(1);
  size[0]  = RcppDeepState_int();
  std::string size_t = "/home/akhila/fuzzer_packages/fuzzedpackages/rayshader/inst/testfiles/subsample/libFuzzer_subsample/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_size.qs";
  qs::c_qsave(size,size_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "size values: "<< size << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    subsample(circle,size[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
