// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// calcEE11_DeepState_TestHarness_generation.cpp and calcEE11_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector calcEE11(NumericVector beta11, NumericVector Y1, NumericVector Y2, NumericVector T1, NumericVector T2, NumericVector Delta1, NumericVector Delta2, NumericMatrix X, NumericMatrix dij11);

TEST(,){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericVector beta11  = RcppDeepState_NumericVector();
  std::string beta11_t = "/home/akhila/fuzzer_packages/fuzzedpackages/mhazard/inst/testfiles/calcEE11/libFuzzer_calcEE11/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_beta11.qs";
  qs::c_qsave(beta11,beta11_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "beta11 values: "<< beta11 << std::endl;
  NumericVector Y1  = RcppDeepState_NumericVector();
  std::string Y1_t = "/home/akhila/fuzzer_packages/fuzzedpackages/mhazard/inst/testfiles/calcEE11/libFuzzer_calcEE11/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_Y1.qs";
  qs::c_qsave(Y1,Y1_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "Y1 values: "<< Y1 << std::endl;
  NumericVector Y2  = RcppDeepState_NumericVector();
  std::string Y2_t = "/home/akhila/fuzzer_packages/fuzzedpackages/mhazard/inst/testfiles/calcEE11/libFuzzer_calcEE11/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_Y2.qs";
  qs::c_qsave(Y2,Y2_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "Y2 values: "<< Y2 << std::endl;
  NumericVector T1  = RcppDeepState_NumericVector();
  std::string T1_t = "/home/akhila/fuzzer_packages/fuzzedpackages/mhazard/inst/testfiles/calcEE11/libFuzzer_calcEE11/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_T1.qs";
  qs::c_qsave(T1,T1_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "T1 values: "<< T1 << std::endl;
  NumericVector T2  = RcppDeepState_NumericVector();
  std::string T2_t = "/home/akhila/fuzzer_packages/fuzzedpackages/mhazard/inst/testfiles/calcEE11/libFuzzer_calcEE11/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_T2.qs";
  qs::c_qsave(T2,T2_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "T2 values: "<< T2 << std::endl;
  NumericVector Delta1  = RcppDeepState_NumericVector();
  std::string Delta1_t = "/home/akhila/fuzzer_packages/fuzzedpackages/mhazard/inst/testfiles/calcEE11/libFuzzer_calcEE11/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_Delta1.qs";
  qs::c_qsave(Delta1,Delta1_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "Delta1 values: "<< Delta1 << std::endl;
  NumericVector Delta2  = RcppDeepState_NumericVector();
  std::string Delta2_t = "/home/akhila/fuzzer_packages/fuzzedpackages/mhazard/inst/testfiles/calcEE11/libFuzzer_calcEE11/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_Delta2.qs";
  qs::c_qsave(Delta2,Delta2_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "Delta2 values: "<< Delta2 << std::endl;
  NumericMatrix X  = RcppDeepState_NumericMatrix();
  std::string X_t = "/home/akhila/fuzzer_packages/fuzzedpackages/mhazard/inst/testfiles/calcEE11/libFuzzer_calcEE11/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_X.qs";
  qs::c_qsave(X,X_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "X values: "<< X << std::endl;
  NumericMatrix dij11  = RcppDeepState_NumericMatrix();
  std::string dij11_t = "/home/akhila/fuzzer_packages/fuzzedpackages/mhazard/inst/testfiles/calcEE11/libFuzzer_calcEE11/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_dij11.qs";
  qs::c_qsave(dij11,dij11_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "dij11 values: "<< dij11 << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    calcEE11(beta11,Y1,Y2,T1,T2,Delta1,Delta2,X,dij11);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
