// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// rspectrum_DeepState_TestHarness_generation.cpp and rspectrum_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

DataFrame rspectrum(arma::mat mat);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  std::ofstream mat_stream;
  arma::mat mat  = RcppDeepState_mat();
  mat_stream.open("/home/akhila/fuzzer_packages/fuzzedpackages/spatialwarnings/inst/testfiles/rspectrum/inputs/mat");
  mat_stream << mat;
  std::cout << "mat values: "<< mat << std::endl;
  mat_stream.close();
  std::cout << "input ends" << std::endl;
  try{
    rspectrum(mat);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
