// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// distanceToPeakCpp_DeepState_TestHarness_generation.cpp and distanceToPeakCpp_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector distanceToPeakCpp(NumericVector distance, NumericVector rho);

TEST(,){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericVector distance  = RcppDeepState_NumericVector();
  std::string distance_t = "/home/akhila/fuzzer_packages/fuzzedpackages/densityClust/inst/testfiles/distanceToPeakCpp/libFuzzer_distanceToPeakCpp/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_distance.qs";
  qs::c_qsave(distance,distance_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "distance values: "<< distance << std::endl;
  NumericVector rho  = RcppDeepState_NumericVector();
  std::string rho_t = "/home/akhila/fuzzer_packages/fuzzedpackages/densityClust/inst/testfiles/distanceToPeakCpp/libFuzzer_distanceToPeakCpp/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_rho.qs";
  qs::c_qsave(rho,rho_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "rho values: "<< rho << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    distanceToPeakCpp(distance,rho);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
