// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// rankSwap_argus_cpp_DeepState_TestHarness_generation.cpp and rankSwap_argus_cpp_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

List rankSwap_argus_cpp(NumericMatrix inp, IntegerVector perc);

TEST(,){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericMatrix inp  = RcppDeepState_NumericMatrix();
  std::string inp_t = "/home/akhila/fuzzer_packages/fuzzedpackages/sdcMicro/inst/testfiles/rankSwap_argus_cpp/libFuzzer_rankSwap_argus_cpp/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_inp.qs";
  qs::c_qsave(inp,inp_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "inp values: "<< inp << std::endl;
  IntegerVector perc  = RcppDeepState_IntegerVector();
  std::string perc_t = "/home/akhila/fuzzer_packages/fuzzedpackages/sdcMicro/inst/testfiles/rankSwap_argus_cpp/libFuzzer_rankSwap_argus_cpp/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_perc.qs";
  qs::c_qsave(perc,perc_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "perc values: "<< perc << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    rankSwap_argus_cpp(inp,perc);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
