// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// tiling_correlogramcpp_DeepState_TestHarness_generation.cpp and tiling_correlogramcpp_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector tiling_correlogramcpp(NumericVector spikes, int n, IntegerVector nspikes, IntegerVector first_spike, double start, double end, /* recording time */                                     double dt, double tau_sep, double tau_max);

TEST(,){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericVector spikes  = RcppDeepState_NumericVector();
  std::string spikes_t = "/home/akhila/fuzzer_packages/fuzzedpackages/meaRtools/inst/testfiles/tiling_correlogramcpp/libFuzzer_tiling_correlogramcpp/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_spikes.qs";
  qs::c_qsave(spikes,spikes_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "spikes values: "<< spikes << std::endl;
  IntegerVector n(1);
  n[0]  = RcppDeepState_int();
  std::string n_t = "/home/akhila/fuzzer_packages/fuzzedpackages/meaRtools/inst/testfiles/tiling_correlogramcpp/libFuzzer_tiling_correlogramcpp/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_n.qs";
  qs::c_qsave(n,n_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "n values: "<< n << std::endl;
  IntegerVector nspikes  = RcppDeepState_IntegerVector();
  std::string n_t = "/home/akhila/fuzzer_packages/fuzzedpackages/meaRtools/inst/testfiles/tiling_correlogramcpp/libFuzzer_tiling_correlogramcpp/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_n.qs";
  std::string nspikes_t = "/home/akhila/fuzzer_packages/fuzzedpackages/meaRtools/inst/testfiles/tiling_correlogramcpp/libFuzzer_tiling_correlogramcpp/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_nspikes.qs";
  qs::c_qsave(nspikes,nspikes_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "nspikes values: "<< nspikes << std::endl;
  IntegerVector first_spike  = RcppDeepState_IntegerVector();
  std::string first_spike_t = "/home/akhila/fuzzer_packages/fuzzedpackages/meaRtools/inst/testfiles/tiling_correlogramcpp/libFuzzer_tiling_correlogramcpp/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_first_spike.qs";
  qs::c_qsave(first_spike,first_spike_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "first_spike values: "<< first_spike << std::endl;
  NumericVector start(1);
  start[0]  = RcppDeepState_double();
  std::string start_t = "/home/akhila/fuzzer_packages/fuzzedpackages/meaRtools/inst/testfiles/tiling_correlogramcpp/libFuzzer_tiling_correlogramcpp/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_start.qs";
  qs::c_qsave(start,start_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "start values: "<< start << std::endl;
  NumericVector end(1);
  end[0]  = RcppDeepState_double();
  std::string end_t = "/home/akhila/fuzzer_packages/fuzzedpackages/meaRtools/inst/testfiles/tiling_correlogramcpp/libFuzzer_tiling_correlogramcpp/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_end.qs";
  qs::c_qsave(end,end_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "end values: "<< end << std::endl;
  NumericVector dt(1);
  dt[0]  = RcppDeepState_double();
  std::string dt_t = "/home/akhila/fuzzer_packages/fuzzedpackages/meaRtools/inst/testfiles/tiling_correlogramcpp/libFuzzer_tiling_correlogramcpp/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_dt.qs";
  qs::c_qsave(dt,dt_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "dt values: "<< dt << std::endl;
  NumericVector tau_sep(1);
  tau_sep[0]  = RcppDeepState_double();
  std::string tau_sep_t = "/home/akhila/fuzzer_packages/fuzzedpackages/meaRtools/inst/testfiles/tiling_correlogramcpp/libFuzzer_tiling_correlogramcpp/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_tau_sep.qs";
  qs::c_qsave(tau_sep,tau_sep_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "tau_sep values: "<< tau_sep << std::endl;
  NumericVector tau_max(1);
  tau_max[0]  = RcppDeepState_double();
  std::string tau_max_t = "/home/akhila/fuzzer_packages/fuzzedpackages/meaRtools/inst/testfiles/tiling_correlogramcpp/libFuzzer_tiling_correlogramcpp/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_tau_max.qs";
  qs::c_qsave(tau_max,tau_max_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "tau_max values: "<< tau_max << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    tiling_correlogramcpp(spikes,n[0],nspikes,first_spike,start[0],end[0],dt[0],tau_sep[0],tau_max[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
