// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// corr_betw_matrices_unpaired_bestpairs_DeepState_TestHarness_generation.cpp and corr_betw_matrices_unpaired_bestpairs_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

List corr_betw_matrices_unpaired_bestpairs(const NumericMatrix& x, const NumericMatrix& y, const double corr_threshold);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericMatrix x  = RcppDeepState_NumericMatrix();
  qs::c_qsave(x,"/home/akhila/fuzzer_packages/fuzzedpackages/lineup2/inst/testfiles/corr_betw_matrices_unpaired_bestpairs/inputs/x.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "x values: "<< x << std::endl;
  NumericMatrix y  = RcppDeepState_NumericMatrix();
  qs::c_qsave(y,"/home/akhila/fuzzer_packages/fuzzedpackages/lineup2/inst/testfiles/corr_betw_matrices_unpaired_bestpairs/inputs/y.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "y values: "<< y << std::endl;
  NumericVector corr_threshold(1);
  corr_threshold[0]  = RcppDeepState_double();
  qs::c_qsave(corr_threshold,"/home/akhila/fuzzer_packages/fuzzedpackages/lineup2/inst/testfiles/corr_betw_matrices_unpaired_bestpairs/inputs/corr_threshold.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "corr_threshold values: "<< corr_threshold << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    corr_betw_matrices_unpaired_bestpairs(x,y,corr_threshold[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
