// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// rcpp_groupmean_DeepState_TestHarness_generation.cpp and rcpp_groupmean_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector rcpp_groupmean(IntegerVector cat_vec, NumericVector val_vec);

TEST(,){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  IntegerVector cat_vec  = RcppDeepState_IntegerVector();
  std::string cat_vec_t = "/home/akhila/fuzzer_packages/fuzzedpackages/raptr/inst/testfiles/rcpp_groupmean/libFuzzer_rcpp_groupmean/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_cat_vec.qs";
  qs::c_qsave(cat_vec,cat_vec_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "cat_vec values: "<< cat_vec << std::endl;
  NumericVector val_vec  = RcppDeepState_NumericVector();
  std::string val_vec_t = "/home/akhila/fuzzer_packages/fuzzedpackages/raptr/inst/testfiles/rcpp_groupmean/libFuzzer_rcpp_groupmean/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_val_vec.qs";
  qs::c_qsave(val_vec,val_vec_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "val_vec values: "<< val_vec << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    rcpp_groupmean(cat_vec,val_vec);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
