// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// set_difference_single_DeepState_TestHarness_generation.cpp and set_difference_single_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

S4 set_difference_single(IntegerVector xi, IntegerVector xp, NumericVector xx, IntegerVector yi, IntegerVector yp, NumericVector yx, int number);

TEST(,){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  IntegerVector xi  = RcppDeepState_IntegerVector();
  std::string xi_t = "/home/akhila/fuzzer_packages/fuzzedpackages/fcaR/inst/testfiles/set_difference_single/libFuzzer_set_difference_single/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_xi.qs";
  qs::c_qsave(xi,xi_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "xi values: "<< xi << std::endl;
  IntegerVector xp  = RcppDeepState_IntegerVector();
  std::string xp_t = "/home/akhila/fuzzer_packages/fuzzedpackages/fcaR/inst/testfiles/set_difference_single/libFuzzer_set_difference_single/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_xp.qs";
  qs::c_qsave(xp,xp_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "xp values: "<< xp << std::endl;
  NumericVector xx  = RcppDeepState_NumericVector();
  std::string xx_t = "/home/akhila/fuzzer_packages/fuzzedpackages/fcaR/inst/testfiles/set_difference_single/libFuzzer_set_difference_single/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_xx.qs";
  qs::c_qsave(xx,xx_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "xx values: "<< xx << std::endl;
  IntegerVector yi  = RcppDeepState_IntegerVector();
  std::string yi_t = "/home/akhila/fuzzer_packages/fuzzedpackages/fcaR/inst/testfiles/set_difference_single/libFuzzer_set_difference_single/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_yi.qs";
  qs::c_qsave(yi,yi_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "yi values: "<< yi << std::endl;
  IntegerVector yp  = RcppDeepState_IntegerVector();
  std::string yp_t = "/home/akhila/fuzzer_packages/fuzzedpackages/fcaR/inst/testfiles/set_difference_single/libFuzzer_set_difference_single/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_yp.qs";
  qs::c_qsave(yp,yp_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "yp values: "<< yp << std::endl;
  NumericVector yx  = RcppDeepState_NumericVector();
  std::string yx_t = "/home/akhila/fuzzer_packages/fuzzedpackages/fcaR/inst/testfiles/set_difference_single/libFuzzer_set_difference_single/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_yx.qs";
  qs::c_qsave(yx,yx_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "yx values: "<< yx << std::endl;
  IntegerVector number(1);
  number[0]  = RcppDeepState_int();
  std::string number_t = "/home/akhila/fuzzer_packages/fuzzedpackages/fcaR/inst/testfiles/set_difference_single/libFuzzer_set_difference_single/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_number.qs";
  qs::c_qsave(number,number_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "number values: "<< number << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    set_difference_single(xi,xp,xx,yi,yp,yx,number[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
