// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// nest2ring_DeepState_TestHarness_generation.cpp and nest2ring_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

IntegerVector nest2ring(int nside, IntegerVector pix);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  IntegerVector nside(1);
  nside[0]  = RcppDeepState_int();
  qs::c_qsave(nside,"/home/akhila/fuzzer_packages/fuzzedpackages/rcosmo/inst/testfiles/nest2ring/inputs/nside.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "nside values: "<< nside << std::endl;
  IntegerVector pix  = RcppDeepState_IntegerVector();
  qs::c_qsave(pix,"/home/akhila/fuzzer_packages/fuzzedpackages/rcosmo/inst/testfiles/nest2ring/inputs/pix.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "pix values: "<< pix << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    nest2ring(nside[0],pix);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
