// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// shuffle_matrix_DeepState_TestHarness_generation.cpp and shuffle_matrix_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

arma::mat shuffle_matrix(arma::mat& mat);

TEST(,){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  std::ofstream mat_stream;
  arma::mat mat  = RcppDeepState_mat();
  mat_stream.open("/home/akhila/fuzzer_packages/fuzzedpackages/spatialwarnings/inst/testfiles/shuffle_matrix/inputs/mat");
  mat_stream << mat;
  std::cout << "mat values: "<< mat << std::endl;
  mat_stream.close();
  std::cout << "input ends" << std::endl;
  try{
    shuffle_matrix(mat);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
