// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// getMedians_DeepState_TestHarness_generation.cpp and getMedians_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

Rcpp::NumericVector getMedians(Rcpp::NumericVector const& x, Rcpp::NumericVector const& wt, Rcpp::IntegerVector const& idx);

TEST(,){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericVector x  = RcppDeepState_NumericVector();
  std::string x_t = "/home/akhila/fuzzer_packages/fuzzedpackages/rpart.LAD/inst/testfiles/getMedians/libFuzzer_getMedians/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_x.qs";
  qs::c_qsave(x,x_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "x values: "<< x << std::endl;
  NumericVector wt  = RcppDeepState_NumericVector();
  std::string wt_t = "/home/akhila/fuzzer_packages/fuzzedpackages/rpart.LAD/inst/testfiles/getMedians/libFuzzer_getMedians/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_wt.qs";
  qs::c_qsave(wt,wt_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "wt values: "<< wt << std::endl;
  IntegerVector idx  = RcppDeepState_IntegerVector();
  std::string idx_t = "/home/akhila/fuzzer_packages/fuzzedpackages/rpart.LAD/inst/testfiles/getMedians/libFuzzer_getMedians/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_idx.qs";
  qs::c_qsave(idx,idx_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "idx values: "<< idx << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    getMedians(x,wt,idx);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
