// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// generateDataFrame_one_both_rcpp_DeepState_TestHarness_generation.cpp and generateDataFrame_one_both_rcpp_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

DataFrame generateDataFrame_one_both_rcpp(NumericMatrix matKernel2, CharacterVector functionNames);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericMatrix matKernel2  = RcppDeepState_NumericMatrix();
  qs::c_qsave(matKernel2,"/home/akhila/fuzzer_packages/fuzzedpackages/SimilaR/inst/testfiles/generateDataFrame_one_both_rcpp/inputs/matKernel2.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "matKernel2 values: "<< matKernel2 << std::endl;
  CharacterVector functionNames  = RcppDeepState_CharacterVector();
  qs::c_qsave(functionNames,"/home/akhila/fuzzer_packages/fuzzedpackages/SimilaR/inst/testfiles/generateDataFrame_one_both_rcpp/inputs/functionNames.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "functionNames values: "<< functionNames << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    generateDataFrame_one_both_rcpp(matKernel2,functionNames);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
