// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// getMedians_DeepState_TestHarness_generation.cpp and getMedians_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

Rcpp::NumericVector getMedians(Rcpp::NumericVector const& x, Rcpp::NumericVector const& wt, Rcpp::IntegerVector const& idx);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector x  = RcppDeepState_NumericVector();
  qs::c_qsave(x,"/home/akhila/fuzzer_packages/fuzzedpackages/rpart.LAD/inst/testfiles/getMedians/inputs/x.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "x values: "<< x << std::endl;
  NumericVector wt  = RcppDeepState_NumericVector();
  qs::c_qsave(wt,"/home/akhila/fuzzer_packages/fuzzedpackages/rpart.LAD/inst/testfiles/getMedians/inputs/wt.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "wt values: "<< wt << std::endl;
  IntegerVector idx  = RcppDeepState_IntegerVector();
  qs::c_qsave(idx,"/home/akhila/fuzzer_packages/fuzzedpackages/rpart.LAD/inst/testfiles/getMedians/inputs/idx.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "idx values: "<< idx << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    getMedians(x,wt,idx);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
