// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// invert_founder_index_DeepState_TestHarness_generation.cpp and invert_founder_index_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

IntegerVector invert_founder_index(IntegerVector cross_info);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  IntegerVector cross_info  = RcppDeepState_IntegerVector();
  qs::c_qsave(cross_info,"/home/akhila/fuzzer_packages/fuzzedpackages/qtl2/inst/testfiles/invert_founder_index/inputs/cross_info.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "cross_info values: "<< cross_info << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    invert_founder_index(cross_info);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
