// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// lazyGreedy_DeepState_TestHarness_generation.cpp and lazyGreedy_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

arma::mat lazyGreedy(const arma::mat& V, double t);

TEST(,){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  std::ofstream V_stream;
  arma::mat V  = RcppDeepState_mat();
  V_stream.open("/home/akhila/fuzzer_packages/fuzzedpackages/lazygreedy/inst/testfiles/lazyGreedy/inputs/V");
  V_stream << V;
  std::cout << "V values: "<< V << std::endl;
  V_stream.close();
  NumericVector t(1);
  t[0]  = RcppDeepState_double();
  std::string t_t = "/home/akhila/fuzzer_packages/fuzzedpackages/lazygreedy/inst/testfiles/lazyGreedy/libFuzzer_lazyGreedy/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_t.qs";
  qs::c_qsave(t,t_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "t values: "<< t << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    lazyGreedy(V,t[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
