// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// random_parent_DeepState_TestHarness_generation.cpp and random_parent_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

IntegerVector random_parent(const IntegerVector nTip, const IntegerVector seed);

TEST(,){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  IntegerVector nTip  = RcppDeepState_IntegerVector();
  std::string nTip_t = "/home/akhila/fuzzer_packages/fuzzedpackages/TreeTools/inst/testfiles/random_parent/libFuzzer_random_parent/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_nTip.qs";
  qs::c_qsave(nTip,nTip_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "nTip values: "<< nTip << std::endl;
  IntegerVector seed  = RcppDeepState_IntegerVector();
  std::string seed_t = "/home/akhila/fuzzer_packages/fuzzedpackages/TreeTools/inst/testfiles/random_parent/libFuzzer_random_parent/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_seed.qs";
  qs::c_qsave(seed,seed_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "seed values: "<< seed << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    random_parent(nTip,seed);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
