// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// cvfolds_DeepState_TestHarness_generation.cpp and cvfolds_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

arma::vec cvfolds(double nfolds, double nrow);

TEST(,){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericVector nfolds(1);
  nfolds[0]  = RcppDeepState_double();
  std::string nfolds_t = "/home/akhila/fuzzer_packages/fuzzedpackages/midasml/inst/testfiles/cvfolds/libFuzzer_cvfolds/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_nfolds.qs";
  qs::c_qsave(nfolds,nfolds_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "nfolds values: "<< nfolds << std::endl;
  NumericVector nrow(1);
  nrow[0]  = RcppDeepState_double();
  std::string nrow_t = "/home/akhila/fuzzer_packages/fuzzedpackages/midasml/inst/testfiles/cvfolds/libFuzzer_cvfolds/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_nrow.qs";
  qs::c_qsave(nrow,nrow_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "nrow values: "<< nrow << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    cvfolds(nfolds[0],nrow[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
