// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// put_val_DeepState_TestHarness_generation.cpp and put_val_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

void put_val(NumericMatrix mtx, int xpos, int ypos, double val);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericMatrix mtx  = RcppDeepState_NumericMatrix();
  qs::c_qsave(mtx,"/home/akhila/fuzzer_packages/fuzzedpackages/maxnodf/inst/testfiles/put_val/inputs/mtx.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "mtx values: "<< mtx << std::endl;
  IntegerVector xpos(1);
  xpos[0]  = RcppDeepState_int();
  qs::c_qsave(xpos,"/home/akhila/fuzzer_packages/fuzzedpackages/maxnodf/inst/testfiles/put_val/inputs/xpos.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "xpos values: "<< xpos << std::endl;
  IntegerVector ypos(1);
  ypos[0]  = RcppDeepState_int();
  qs::c_qsave(ypos,"/home/akhila/fuzzer_packages/fuzzedpackages/maxnodf/inst/testfiles/put_val/inputs/ypos.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "ypos values: "<< ypos << std::endl;
  NumericVector val(1);
  val[0]  = RcppDeepState_double();
  qs::c_qsave(val,"/home/akhila/fuzzer_packages/fuzzedpackages/maxnodf/inst/testfiles/put_val/inputs/val.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "val values: "<< val << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    put_val(mtx,xpos[0],ypos[0],val[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
