// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// cubic_interpolate_DeepState_TestHarness_generation.cpp and cubic_interpolate_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

double cubic_interpolate(double p0, double p1, double p2, double p3, double x);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector p0(1);
  p0[0]  = RcppDeepState_double();
  qs::c_qsave(p0,"/home/akhila/fuzzer_packages/fuzzedpackages/rayshader/inst/testfiles/cubic_interpolate/inputs/p0.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "p0 values: "<< p0 << std::endl;
  NumericVector p1(1);
  p1[0]  = RcppDeepState_double();
  qs::c_qsave(p1,"/home/akhila/fuzzer_packages/fuzzedpackages/rayshader/inst/testfiles/cubic_interpolate/inputs/p1.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "p1 values: "<< p1 << std::endl;
  NumericVector p2(1);
  p2[0]  = RcppDeepState_double();
  qs::c_qsave(p2,"/home/akhila/fuzzer_packages/fuzzedpackages/rayshader/inst/testfiles/cubic_interpolate/inputs/p2.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "p2 values: "<< p2 << std::endl;
  NumericVector p3(1);
  p3[0]  = RcppDeepState_double();
  qs::c_qsave(p3,"/home/akhila/fuzzer_packages/fuzzedpackages/rayshader/inst/testfiles/cubic_interpolate/inputs/p3.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "p3 values: "<< p3 << std::endl;
  NumericVector x(1);
  x[0]  = RcppDeepState_double();
  qs::c_qsave(x,"/home/akhila/fuzzer_packages/fuzzedpackages/rayshader/inst/testfiles/cubic_interpolate/inputs/x.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "x values: "<< x << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    cubic_interpolate(p0[0],p1[0],p2[0],p3[0],x[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
