// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// computeFill0_DeepState_TestHarness_generation.cpp and computeFill0_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericMatrix computeFill0(NumericMatrix mtx);

TEST(,){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericMatrix mtx  = RcppDeepState_NumericMatrix();
  std::string mtx_t = "/home/akhila/fuzzer_packages/fuzzedpackages/maxnodf/inst/testfiles/computeFill0/libFuzzer_computeFill0/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_mtx.qs";
  qs::c_qsave(mtx,mtx_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "mtx values: "<< mtx << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    computeFill0(mtx);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
