// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// permute_ivector_stratified_DeepState_TestHarness_generation.cpp and permute_ivector_stratified_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

IntegerMatrix permute_ivector_stratified(const int n_perm, const IntegerVector& x, const IntegerVector& strata, int n_strata);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  IntegerVector n_perm(1);
  n_perm[0]  = RcppDeepState_int();
  qs::c_qsave(n_perm,"/home/akhila/fuzzer_packages/fuzzedpackages/qtl2/inst/testfiles/permute_ivector_stratified/inputs/n_perm.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "n_perm values: "<< n_perm << std::endl;
  IntegerVector x  = RcppDeepState_IntegerVector();
  qs::c_qsave(x,"/home/akhila/fuzzer_packages/fuzzedpackages/qtl2/inst/testfiles/permute_ivector_stratified/inputs/x.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "x values: "<< x << std::endl;
  IntegerVector strata  = RcppDeepState_IntegerVector();
  qs::c_qsave(strata,"/home/akhila/fuzzer_packages/fuzzedpackages/qtl2/inst/testfiles/permute_ivector_stratified/inputs/strata.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "strata values: "<< strata << std::endl;
  IntegerVector n_strata(1);
  n_strata[0]  = RcppDeepState_int();
  qs::c_qsave(n_strata,"/home/akhila/fuzzer_packages/fuzzedpackages/qtl2/inst/testfiles/permute_ivector_stratified/inputs/n_strata.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "n_strata values: "<< n_strata << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    permute_ivector_stratified(n_perm[0],x,strata,n_strata[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
