// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// varcoef_DeepState_TestHarness_generation.cpp and varcoef_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

Rcpp::NumericMatrix varcoef(const arma::mat& coef, const arma::mat& X);

TEST(,){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  std::ofstream coef_stream;
  arma::mat coef  = RcppDeepState_mat();
  coef_stream.open("/home/akhila/fuzzer_packages/fuzzedpackages/seqHMM/inst/testfiles/varcoef/inputs/coef");
  coef_stream << coef;
  std::cout << "coef values: "<< coef << std::endl;
  coef_stream.close();
  std::ofstream X_stream;
  arma::mat X  = RcppDeepState_mat();
  X_stream.open("/home/akhila/fuzzer_packages/fuzzedpackages/seqHMM/inst/testfiles/varcoef/inputs/X");
  X_stream << X;
  std::cout << "X values: "<< X << std::endl;
  X_stream.close();
  std::cout << "input ends" << std::endl;
  try{
    varcoef(coef,X);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
