// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// genSizeComp2_DeepState_TestHarness_generation.cpp and genSizeComp2_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericMatrix genSizeComp2(NumericMatrix VulnN, NumericVector CAL_binsmid, NumericVector CAL_bins, NumericMatrix selCurve, double CAL_ESS, double CAL_nsamp, NumericVector Linfs, NumericVector Ks, NumericVector t0s, double LenCV, double truncSD);

TEST(,){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericMatrix VulnN  = RcppDeepState_NumericMatrix();
  std::string VulnN_t = "/home/akhila/fuzzer_packages/fuzzedpackages/MSEtool/inst/testfiles/genSizeComp2/libFuzzer_genSizeComp2/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_VulnN.qs";
  qs::c_qsave(VulnN,VulnN_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "VulnN values: "<< VulnN << std::endl;
  NumericVector CAL_binsmid  = RcppDeepState_NumericVector();
  std::string CAL_binsmid_t = "/home/akhila/fuzzer_packages/fuzzedpackages/MSEtool/inst/testfiles/genSizeComp2/libFuzzer_genSizeComp2/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_CAL_binsmid.qs";
  std::string CAL_bins_t = "/home/akhila/fuzzer_packages/fuzzedpackages/MSEtool/inst/testfiles/genSizeComp2/libFuzzer_genSizeComp2/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_CAL_bins.qs";
  qs::c_qsave(CAL_binsmid,CAL_binsmid_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "CAL_binsmid values: "<< CAL_binsmid << std::endl;
  NumericVector CAL_bins  = RcppDeepState_NumericVector();
  std::string CAL_bins_t = "/home/akhila/fuzzer_packages/fuzzedpackages/MSEtool/inst/testfiles/genSizeComp2/libFuzzer_genSizeComp2/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_CAL_bins.qs";
  qs::c_qsave(CAL_bins,CAL_bins_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "CAL_bins values: "<< CAL_bins << std::endl;
  NumericMatrix selCurve  = RcppDeepState_NumericMatrix();
  std::string selCurve_t = "/home/akhila/fuzzer_packages/fuzzedpackages/MSEtool/inst/testfiles/genSizeComp2/libFuzzer_genSizeComp2/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_selCurve.qs";
  qs::c_qsave(selCurve,selCurve_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "selCurve values: "<< selCurve << std::endl;
  NumericVector CAL_ESS(1);
  CAL_ESS[0]  = RcppDeepState_double();
  std::string CAL_ESS_t = "/home/akhila/fuzzer_packages/fuzzedpackages/MSEtool/inst/testfiles/genSizeComp2/libFuzzer_genSizeComp2/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_CAL_ESS.qs";
  qs::c_qsave(CAL_ESS,CAL_ESS_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "CAL_ESS values: "<< CAL_ESS << std::endl;
  NumericVector CAL_nsamp(1);
  CAL_nsamp[0]  = RcppDeepState_double();
  std::string CAL_nsamp_t = "/home/akhila/fuzzer_packages/fuzzedpackages/MSEtool/inst/testfiles/genSizeComp2/libFuzzer_genSizeComp2/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_CAL_nsamp.qs";
  qs::c_qsave(CAL_nsamp,CAL_nsamp_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "CAL_nsamp values: "<< CAL_nsamp << std::endl;
  NumericVector Linfs  = RcppDeepState_NumericVector();
  std::string Linfs_t = "/home/akhila/fuzzer_packages/fuzzedpackages/MSEtool/inst/testfiles/genSizeComp2/libFuzzer_genSizeComp2/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_Linfs.qs";
  qs::c_qsave(Linfs,Linfs_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "Linfs values: "<< Linfs << std::endl;
  NumericVector Ks  = RcppDeepState_NumericVector();
  std::string Ks_t = "/home/akhila/fuzzer_packages/fuzzedpackages/MSEtool/inst/testfiles/genSizeComp2/libFuzzer_genSizeComp2/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_Ks.qs";
  qs::c_qsave(Ks,Ks_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "Ks values: "<< Ks << std::endl;
  NumericVector t0s  = RcppDeepState_NumericVector();
  std::string t0s_t = "/home/akhila/fuzzer_packages/fuzzedpackages/MSEtool/inst/testfiles/genSizeComp2/libFuzzer_genSizeComp2/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_t0s.qs";
  qs::c_qsave(t0s,t0s_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "t0s values: "<< t0s << std::endl;
  NumericVector LenCV(1);
  LenCV[0]  = RcppDeepState_double();
  std::string LenCV_t = "/home/akhila/fuzzer_packages/fuzzedpackages/MSEtool/inst/testfiles/genSizeComp2/libFuzzer_genSizeComp2/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_LenCV.qs";
  qs::c_qsave(LenCV,LenCV_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "LenCV values: "<< LenCV << std::endl;
  NumericVector truncSD(1);
  truncSD[0]  = RcppDeepState_double();
  std::string truncSD_t = "/home/akhila/fuzzer_packages/fuzzedpackages/MSEtool/inst/testfiles/genSizeComp2/libFuzzer_genSizeComp2/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_truncSD.qs";
  qs::c_qsave(truncSD,truncSD_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "truncSD values: "<< truncSD << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    genSizeComp2(VulnN,CAL_binsmid,CAL_bins,selCurve,CAL_ESS[0],CAL_nsamp[0],Linfs,Ks,t0s,LenCV[0],truncSD[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
