// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// inversa_DeepState_TestHarness_generation.cpp and inversa_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

arma::mat inversa(arma::mat M);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  std::ofstream M_stream;
  arma::mat M  = RcppDeepState_mat();
  M_stream.open("/home/akhila/fuzzer_packages/fuzzedpackages/StempCens/inst/testfiles/inversa/inputs/M");
  M_stream << M;
  std::cout << "M values: "<< M << std::endl;
  M_stream.close();
  std::cout << "input ends" << std::endl;
  try{
    inversa(M);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
