// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// sum_all_one_over_k_before_DeepState_TestHarness_generation.cpp and sum_all_one_over_k_before_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

double sum_all_one_over_k_before(int n, double expo);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  IntegerVector n(1);
  n[0]  = RcppDeepState_int();
  qs::c_qsave(n,"/home/akhila/fuzzer_packages/fuzzedpackages/spatialwarnings/inst/testfiles/sum_all_one_over_k_before/inputs/n.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "n values: "<< n << std::endl;
  NumericVector expo(1);
  expo[0]  = RcppDeepState_double();
  qs::c_qsave(expo,"/home/akhila/fuzzer_packages/fuzzedpackages/spatialwarnings/inst/testfiles/sum_all_one_over_k_before/inputs/expo.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "expo values: "<< expo << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    sum_all_one_over_k_before(n[0],expo[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
