// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// NuMatParC_DeepState_TestHarness_generation.cpp and NuMatParC_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

List NuMatParC(const NumericVector& c, const arma::mat& d);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector c  = RcppDeepState_NumericVector();
  qs::c_qsave(c,"/home/akhila/fuzzer_packages/fuzzedpackages/NPflow/inst/testfiles/NuMatParC/inputs/c.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "c values: "<< c << std::endl;
  std::ofstream d_stream;
  arma::mat d  = RcppDeepState_mat();
  d_stream.open("/home/akhila/fuzzer_packages/fuzzedpackages/NPflow/inst/testfiles/NuMatParC/inputs/d");
  d_stream << d;
  std::cout << "d values: "<< d << std::endl;
  d_stream.close();
  std::cout << "input ends" << std::endl;
  try{
    NuMatParC(c,d);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
