// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// bilineargrid_DeepState_TestHarness_generation.cpp and bilineargrid_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericMatrix bilineargrid(NumericMatrix& colorarray);

TEST(,){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericMatrix colorarray  = RcppDeepState_NumericMatrix();
  std::string colorarray_t = "/home/akhila/fuzzer_packages/fuzzedpackages/rayshader/inst/testfiles/bilineargrid/libFuzzer_bilineargrid/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_colorarray.qs";
  qs::c_qsave(colorarray,colorarray_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "colorarray values: "<< colorarray << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    bilineargrid(colorarray);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
