// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// fastclarans_DeepState_TestHarness_generation.cpp and fastclarans_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

S4 fastclarans(NumericVector rdist, int n, int k, int numlocal, double maxneighbor, int seed);

TEST(,){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericVector rdist  = RcppDeepState_NumericVector();
  std::string rdist_t = "/home/akhila/fuzzer_packages/fuzzedpackages/fastkmedoids/inst/testfiles/fastclarans/libFuzzer_fastclarans/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_rdist.qs";
  qs::c_qsave(rdist,rdist_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "rdist values: "<< rdist << std::endl;
  IntegerVector n(1);
  n[0]  = RcppDeepState_int();
  std::string n_t = "/home/akhila/fuzzer_packages/fuzzedpackages/fastkmedoids/inst/testfiles/fastclarans/libFuzzer_fastclarans/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_n.qs";
  qs::c_qsave(n,n_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "n values: "<< n << std::endl;
  IntegerVector k(1);
  k[0]  = RcppDeepState_int();
  std::string k_t = "/home/akhila/fuzzer_packages/fuzzedpackages/fastkmedoids/inst/testfiles/fastclarans/libFuzzer_fastclarans/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_k.qs";
  qs::c_qsave(k,k_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "k values: "<< k << std::endl;
  IntegerVector numlocal(1);
  numlocal[0]  = RcppDeepState_int();
  std::string n_t = "/home/akhila/fuzzer_packages/fuzzedpackages/fastkmedoids/inst/testfiles/fastclarans/libFuzzer_fastclarans/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_n.qs";
  std::string numlocal_t = "/home/akhila/fuzzer_packages/fuzzedpackages/fastkmedoids/inst/testfiles/fastclarans/libFuzzer_fastclarans/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_numlocal.qs";
  qs::c_qsave(numlocal,numlocal_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "numlocal values: "<< numlocal << std::endl;
  NumericVector maxneighbor(1);
  maxneighbor[0]  = RcppDeepState_double();
  std::string maxneighbor_t = "/home/akhila/fuzzer_packages/fuzzedpackages/fastkmedoids/inst/testfiles/fastclarans/libFuzzer_fastclarans/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_maxneighbor.qs";
  qs::c_qsave(maxneighbor,maxneighbor_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "maxneighbor values: "<< maxneighbor << std::endl;
  IntegerVector seed(1);
  seed[0]  = RcppDeepState_int();
  std::string seed_t = "/home/akhila/fuzzer_packages/fuzzedpackages/fastkmedoids/inst/testfiles/fastclarans/libFuzzer_fastclarans/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_seed.qs";
  qs::c_qsave(seed,seed_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "seed values: "<< seed << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    fastclarans(rdist,n[0],k[0],numlocal[0],maxneighbor[0],seed[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
