// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// getSij_DeepState_TestHarness_generation.cpp and getSij_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericMatrix getSij(const NumericMatrix& expmu, const NumericVector& expdelta, const IntegerVector& cdindex);

TEST(,){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericMatrix expmu  = RcppDeepState_NumericMatrix();
  std::string expmu_t = "/home/akhila/fuzzer_packages/fuzzedpackages/BLPestimatoR/inst/testfiles/getSij/libFuzzer_getSij/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_expmu.qs";
  qs::c_qsave(expmu,expmu_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "expmu values: "<< expmu << std::endl;
  NumericVector expdelta  = RcppDeepState_NumericVector();
  std::string expdelta_t = "/home/akhila/fuzzer_packages/fuzzedpackages/BLPestimatoR/inst/testfiles/getSij/libFuzzer_getSij/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_expdelta.qs";
  qs::c_qsave(expdelta,expdelta_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "expdelta values: "<< expdelta << std::endl;
  IntegerVector cdindex  = RcppDeepState_IntegerVector();
  std::string cdindex_t = "/home/akhila/fuzzer_packages/fuzzedpackages/BLPestimatoR/inst/testfiles/getSij/libFuzzer_getSij/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_cdindex.qs";
  qs::c_qsave(cdindex,cdindex_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "cdindex values: "<< cdindex << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    getSij(expmu,expdelta,cdindex);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
