// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// Bpert_DeepState_TestHarness_generation.cpp and Bpert_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

arma::mat Bpert(int bsize, int tr_num);

TEST(,){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  IntegerVector bsize(1);
  bsize[0]  = RcppDeepState_int();
  std::string bsize_t = "/home/akhila/fuzzer_packages/fuzzedpackages/carat/inst/testfiles/Bpert/libFuzzer_Bpert/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_bsize.qs";
  qs::c_qsave(bsize,bsize_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "bsize values: "<< bsize << std::endl;
  IntegerVector tr_num(1);
  tr_num[0]  = RcppDeepState_int();
  std::string tr_num_t = "/home/akhila/fuzzer_packages/fuzzedpackages/carat/inst/testfiles/Bpert/libFuzzer_Bpert/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_tr_num.qs";
  qs::c_qsave(tr_num,tr_num_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "tr_num values: "<< tr_num << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    Bpert(bsize[0],tr_num[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
