// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// permute_ivector_DeepState_TestHarness_generation.cpp and permute_ivector_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

IntegerMatrix permute_ivector(const int n_perm, const IntegerVector x);

TEST(,){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  IntegerVector n_perm(1);
  n_perm[0]  = RcppDeepState_int();
  std::string n_perm_t = "/home/akhila/fuzzer_packages/fuzzedpackages/qtl2/inst/testfiles/permute_ivector/libFuzzer_permute_ivector/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_n_perm.qs";
  qs::c_qsave(n_perm,n_perm_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "n_perm values: "<< n_perm << std::endl;
  IntegerVector x  = RcppDeepState_IntegerVector();
  std::string x_t = "/home/akhila/fuzzer_packages/fuzzedpackages/qtl2/inst/testfiles/permute_ivector/libFuzzer_permute_ivector/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_x.qs";
  qs::c_qsave(x,x_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "x values: "<< x << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    permute_ivector(n_perm[0],x);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
