// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// calcEE11_DeepState_TestHarness_generation.cpp and calcEE11_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector calcEE11(NumericVector beta11, NumericVector Y1, NumericVector Y2, NumericVector T1, NumericVector T2, NumericVector Delta1, NumericVector Delta2, NumericMatrix X, NumericMatrix dij11);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector beta11  = RcppDeepState_NumericVector();
  qs::c_qsave(beta11,"/home/akhila/fuzzer_packages/fuzzedpackages/mhazard/inst/testfiles/calcEE11/inputs/beta11.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "beta11 values: "<< beta11 << std::endl;
  NumericVector Y1  = RcppDeepState_NumericVector();
  qs::c_qsave(Y1,"/home/akhila/fuzzer_packages/fuzzedpackages/mhazard/inst/testfiles/calcEE11/inputs/Y1.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "Y1 values: "<< Y1 << std::endl;
  NumericVector Y2  = RcppDeepState_NumericVector();
  qs::c_qsave(Y2,"/home/akhila/fuzzer_packages/fuzzedpackages/mhazard/inst/testfiles/calcEE11/inputs/Y2.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "Y2 values: "<< Y2 << std::endl;
  NumericVector T1  = RcppDeepState_NumericVector();
  qs::c_qsave(T1,"/home/akhila/fuzzer_packages/fuzzedpackages/mhazard/inst/testfiles/calcEE11/inputs/T1.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "T1 values: "<< T1 << std::endl;
  NumericVector T2  = RcppDeepState_NumericVector();
  qs::c_qsave(T2,"/home/akhila/fuzzer_packages/fuzzedpackages/mhazard/inst/testfiles/calcEE11/inputs/T2.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "T2 values: "<< T2 << std::endl;
  NumericVector Delta1  = RcppDeepState_NumericVector();
  qs::c_qsave(Delta1,"/home/akhila/fuzzer_packages/fuzzedpackages/mhazard/inst/testfiles/calcEE11/inputs/Delta1.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "Delta1 values: "<< Delta1 << std::endl;
  NumericVector Delta2  = RcppDeepState_NumericVector();
  qs::c_qsave(Delta2,"/home/akhila/fuzzer_packages/fuzzedpackages/mhazard/inst/testfiles/calcEE11/inputs/Delta2.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "Delta2 values: "<< Delta2 << std::endl;
  NumericMatrix X  = RcppDeepState_NumericMatrix();
  qs::c_qsave(X,"/home/akhila/fuzzer_packages/fuzzedpackages/mhazard/inst/testfiles/calcEE11/inputs/X.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "X values: "<< X << std::endl;
  NumericMatrix dij11  = RcppDeepState_NumericMatrix();
  qs::c_qsave(dij11,"/home/akhila/fuzzer_packages/fuzzedpackages/mhazard/inst/testfiles/calcEE11/inputs/dij11.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "dij11 values: "<< dij11 << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    calcEE11(beta11,Y1,Y2,T1,T2,Delta1,Delta2,X,dij11);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
