// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// rowSumsSq_DeepState_TestHarness_generation.cpp and rowSumsSq_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector rowSumsSq(const NumericMatrix& source);

TEST(,){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericMatrix source  = RcppDeepState_NumericMatrix();
  std::string source_t = "/home/akhila/fuzzer_packages/fuzzedpackages/bigutilsr/inst/testfiles/rowSumsSq/libFuzzer_rowSumsSq/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_source.qs";
  qs::c_qsave(source,source_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "source values: "<< source << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    rowSumsSq(source);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
