// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// revert_dist_list_cpp_DeepState_TestHarness_generation.cpp and revert_dist_list_cpp_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

List revert_dist_list_cpp(int n_t, int n_c, NumericVector startn, NumericVector endn, NumericVector d);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  IntegerVector n_t(1);
  n_t[0]  = RcppDeepState_int();
  qs::c_qsave(n_t,"/home/akhila/fuzzer_packages/fuzzedpackages/match2C/inst/testfiles/revert_dist_list_cpp/inputs/n_t.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "n_t values: "<< n_t << std::endl;
  IntegerVector n_c(1);
  n_c[0]  = RcppDeepState_int();
  qs::c_qsave(n_c,"/home/akhila/fuzzer_packages/fuzzedpackages/match2C/inst/testfiles/revert_dist_list_cpp/inputs/n_c.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "n_c values: "<< n_c << std::endl;
  NumericVector startn  = RcppDeepState_NumericVector();
  qs::c_qsave(startn,"/home/akhila/fuzzer_packages/fuzzedpackages/match2C/inst/testfiles/revert_dist_list_cpp/inputs/startn.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "startn values: "<< startn << std::endl;
  NumericVector endn  = RcppDeepState_NumericVector();
  qs::c_qsave(endn,"/home/akhila/fuzzer_packages/fuzzedpackages/match2C/inst/testfiles/revert_dist_list_cpp/inputs/endn.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "endn values: "<< endn << std::endl;
  NumericVector d  = RcppDeepState_NumericVector();
  qs::c_qsave(d,"/home/akhila/fuzzer_packages/fuzzedpackages/match2C/inst/testfiles/revert_dist_list_cpp/inputs/d.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "d values: "<< d << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    revert_dist_list_cpp(n_t[0],n_c[0],startn,endn,d);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
