// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// arrange_genes_DeepState_TestHarness_generation.cpp and arrange_genes_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

IntegerVector arrange_genes(const NumericVector& start, const NumericVector& end);

TEST(,){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericVector start  = RcppDeepState_NumericVector();
  std::string start_t = "/home/akhila/fuzzer_packages/fuzzedpackages/qtl2/inst/testfiles/arrange_genes/libFuzzer_arrange_genes/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_start.qs";
  qs::c_qsave(start,start_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "start values: "<< start << std::endl;
  NumericVector end  = RcppDeepState_NumericVector();
  std::string end_t = "/home/akhila/fuzzer_packages/fuzzedpackages/qtl2/inst/testfiles/arrange_genes/libFuzzer_arrange_genes/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_end.qs";
  qs::c_qsave(end,end_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "end values: "<< end << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    arrange_genes(start,end);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
