// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// edge_to_num_DeepState_TestHarness_generation.cpp and edge_to_num_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

IntegerVector edge_to_num(IntegerVector parent, IntegerVector child, IntegerVector nTip);

TEST(,){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  IntegerVector parent  = RcppDeepState_IntegerVector();
  std::string parent_t = "/home/akhila/fuzzer_packages/fuzzedpackages/TreeTools/inst/testfiles/edge_to_num/libFuzzer_edge_to_num/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_parent.qs";
  qs::c_qsave(parent,parent_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "parent values: "<< parent << std::endl;
  IntegerVector child  = RcppDeepState_IntegerVector();
  std::string child_t = "/home/akhila/fuzzer_packages/fuzzedpackages/TreeTools/inst/testfiles/edge_to_num/libFuzzer_edge_to_num/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_child.qs";
  qs::c_qsave(child,child_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "child values: "<< child << std::endl;
  IntegerVector nTip  = RcppDeepState_IntegerVector();
  std::string nTip_t = "/home/akhila/fuzzer_packages/fuzzedpackages/TreeTools/inst/testfiles/edge_to_num/libFuzzer_edge_to_num/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_nTip.qs";
  qs::c_qsave(nTip,nTip_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "nTip values: "<< nTip << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    edge_to_num(parent,child,nTip);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
