// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// row_var_dgcmatrix_DeepState_TestHarness_generation.cpp and row_var_dgcmatrix_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector row_var_dgcmatrix(NumericVector x, IntegerVector i, int rows, int cols);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector x  = RcppDeepState_NumericVector();
  qs::c_qsave(x,"/home/akhila/fuzzer_packages/fuzzedpackages/sctransform/inst/testfiles/row_var_dgcmatrix/inputs/x.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "x values: "<< x << std::endl;
  IntegerVector i  = RcppDeepState_IntegerVector();
  qs::c_qsave(i,"/home/akhila/fuzzer_packages/fuzzedpackages/sctransform/inst/testfiles/row_var_dgcmatrix/inputs/i.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "i values: "<< i << std::endl;
  IntegerVector rows(1);
  rows[0]  = RcppDeepState_int();
  qs::c_qsave(rows,"/home/akhila/fuzzer_packages/fuzzedpackages/sctransform/inst/testfiles/row_var_dgcmatrix/inputs/rows.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "rows values: "<< rows << std::endl;
  IntegerVector cols(1);
  cols[0]  = RcppDeepState_int();
  qs::c_qsave(cols,"/home/akhila/fuzzer_packages/fuzzedpackages/sctransform/inst/testfiles/row_var_dgcmatrix/inputs/cols.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "cols values: "<< cols << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    row_var_dgcmatrix(x,i,rows[0],cols[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
