// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// rooted_shape_to_edge_DeepState_TestHarness_generation.cpp and rooted_shape_to_edge_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

IntegerMatrix rooted_shape_to_edge(NumericVector shape, IntegerVector nTip);

TEST(,){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericVector shape  = RcppDeepState_NumericVector();
  std::string shape_t = "/home/akhila/fuzzer_packages/fuzzedpackages/TreeTools/inst/testfiles/rooted_shape_to_edge/libFuzzer_rooted_shape_to_edge/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_shape.qs";
  qs::c_qsave(shape,shape_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "shape values: "<< shape << std::endl;
  IntegerVector nTip  = RcppDeepState_IntegerVector();
  std::string nTip_t = "/home/akhila/fuzzer_packages/fuzzedpackages/TreeTools/inst/testfiles/rooted_shape_to_edge/libFuzzer_rooted_shape_to_edge/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_nTip.qs";
  qs::c_qsave(nTip,nTip_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "nTip values: "<< nTip << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    rooted_shape_to_edge(shape,nTip);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
