// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// rcpp_proportion_held_DeepState_TestHarness_generation.cpp and rcpp_proportion_held_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

double rcpp_proportion_held(Rcpp::NumericMatrix x, Rcpp::NumericMatrix y, Rcpp::NumericVector y_weights);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericMatrix x  = RcppDeepState_NumericMatrix();
  qs::c_qsave(x,"/home/akhila/fuzzer_packages/fuzzedpackages/raptr/inst/testfiles/rcpp_proportion_held/inputs/x.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "x values: "<< x << std::endl;
  NumericMatrix y  = RcppDeepState_NumericMatrix();
  qs::c_qsave(y,"/home/akhila/fuzzer_packages/fuzzedpackages/raptr/inst/testfiles/rcpp_proportion_held/inputs/y.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "y values: "<< y << std::endl;
  NumericVector y_weights  = RcppDeepState_NumericVector();
  qs::c_qsave(y_weights,"/home/akhila/fuzzer_packages/fuzzedpackages/raptr/inst/testfiles/rcpp_proportion_held/inputs/y_weights.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "y_weights values: "<< y_weights << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    rcpp_proportion_held(x,y,y_weights);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
