// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// calcF_DeepState_TestHarness_generation.cpp and calcF_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericMatrix calcF(NumericVector lambda10, NumericVector lambda01, NumericMatrix lambda11);

TEST(,){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericVector lambda10  = RcppDeepState_NumericVector();
  std::string lambda10_t = "/home/akhila/fuzzer_packages/fuzzedpackages/mhazard/inst/testfiles/calcF/libFuzzer_calcF/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_lambda10.qs";
  qs::c_qsave(lambda10,lambda10_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "lambda10 values: "<< lambda10 << std::endl;
  NumericVector lambda01  = RcppDeepState_NumericVector();
  std::string lambda01_t = "/home/akhila/fuzzer_packages/fuzzedpackages/mhazard/inst/testfiles/calcF/libFuzzer_calcF/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_lambda01.qs";
  qs::c_qsave(lambda01,lambda01_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "lambda01 values: "<< lambda01 << std::endl;
  NumericMatrix lambda11  = RcppDeepState_NumericMatrix();
  std::string lambda11_t = "/home/akhila/fuzzer_packages/fuzzedpackages/mhazard/inst/testfiles/calcF/libFuzzer_calcF/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_lambda11.qs";
  qs::c_qsave(lambda11,lambda11_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "lambda11 values: "<< lambda11 << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    calcF(lambda10,lambda01,lambda11);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
