// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// unvectorize_DeepState_TestHarness_generation.cpp and unvectorize_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericMatrix unvectorize(const NumericVector& vect);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector vect  = RcppDeepState_NumericVector();
  qs::c_qsave(vect,"/home/akhila/fuzzer_packages/fuzzedpackages/TestCor/inst/testfiles/unvectorize/inputs/vect.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "vect values: "<< vect << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    unvectorize(vect);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
