// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// SurvDump_DeepState_TestHarness_generation.cpp and SurvDump_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

SEXP SurvDump(int year, int sex);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  IntegerVector year(1);
  year[0]  = RcppDeepState_int();
  qs::c_qsave(year,"/home/akhila/fuzzer_packages/fuzzedpackages/missDeaths/inst/testfiles/SurvDump/inputs/year.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "year values: "<< year << std::endl;
  IntegerVector sex(1);
  sex[0]  = RcppDeepState_int();
  qs::c_qsave(sex,"/home/akhila/fuzzer_packages/fuzzedpackages/missDeaths/inst/testfiles/SurvDump/inputs/sex.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "sex values: "<< sex << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    SurvDump(year[0],sex[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
