// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// sample_path_mr_DeepState_TestHarness_generation.cpp and sample_path_mr_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

arma::mat sample_path_mr(const int a, const int b, const double t0, const double t1, const Rcpp::NumericMatrix& Q);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  IntegerVector a(1);
  a[0]  = RcppDeepState_int();
  qs::c_qsave(a,"/home/akhila/fuzzer_packages/fuzzedpackages/ECctmc/inst/testfiles/sample_path_mr/inputs/a.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "a values: "<< a << std::endl;
  IntegerVector b(1);
  b[0]  = RcppDeepState_int();
  qs::c_qsave(b,"/home/akhila/fuzzer_packages/fuzzedpackages/ECctmc/inst/testfiles/sample_path_mr/inputs/b.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "b values: "<< b << std::endl;
  NumericVector t0(1);
  t0[0]  = RcppDeepState_double();
  qs::c_qsave(t0,"/home/akhila/fuzzer_packages/fuzzedpackages/ECctmc/inst/testfiles/sample_path_mr/inputs/t0.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "t0 values: "<< t0 << std::endl;
  NumericVector t1(1);
  t1[0]  = RcppDeepState_double();
  qs::c_qsave(t1,"/home/akhila/fuzzer_packages/fuzzedpackages/ECctmc/inst/testfiles/sample_path_mr/inputs/t1.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "t1 values: "<< t1 << std::endl;
  NumericMatrix Q  = RcppDeepState_NumericMatrix();
  qs::c_qsave(Q,"/home/akhila/fuzzer_packages/fuzzedpackages/ECctmc/inst/testfiles/sample_path_mr/inputs/Q.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "Q values: "<< Q << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    sample_path_mr(a[0],b[0],t0[0],t1[0],Q);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
