// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// cpp_chisq_DeepState_TestHarness_generation.cpp and cpp_chisq_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

double cpp_chisq(const IntegerVector& T1, const IntegerVector& T2, const IntegerVector& Tsum);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  IntegerVector T1  = RcppDeepState_IntegerVector();
  qs::c_qsave(T1,"/home/akhila/fuzzer_packages/fuzzedpackages/rainette/inst/testfiles/cpp_chisq/inputs/T1.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "T1 values: "<< T1 << std::endl;
  IntegerVector T2  = RcppDeepState_IntegerVector();
  qs::c_qsave(T2,"/home/akhila/fuzzer_packages/fuzzedpackages/rainette/inst/testfiles/cpp_chisq/inputs/T2.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "T2 values: "<< T2 << std::endl;
  IntegerVector Tsum  = RcppDeepState_IntegerVector();
  qs::c_qsave(Tsum,"/home/akhila/fuzzer_packages/fuzzedpackages/rainette/inst/testfiles/cpp_chisq/inputs/Tsum.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "Tsum values: "<< Tsum << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    cpp_chisq(T1,T2,Tsum);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
