// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// scan_hk_onechr_intcovar_highmem_DeepState_TestHarness_generation.cpp and scan_hk_onechr_intcovar_highmem_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericMatrix scan_hk_onechr_intcovar_highmem(const NumericVector& genoprobs, const NumericMatrix& pheno, const NumericMatrix& addcovar, const NumericMatrix& intcovar, const double tol);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector genoprobs  = RcppDeepState_NumericVector();
  qs::c_qsave(genoprobs,"/home/akhila/fuzzer_packages/fuzzedpackages/qtl2/inst/testfiles/scan_hk_onechr_intcovar_highmem/inputs/genoprobs.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "genoprobs values: "<< genoprobs << std::endl;
  NumericMatrix pheno  = RcppDeepState_NumericMatrix();
  qs::c_qsave(pheno,"/home/akhila/fuzzer_packages/fuzzedpackages/qtl2/inst/testfiles/scan_hk_onechr_intcovar_highmem/inputs/pheno.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "pheno values: "<< pheno << std::endl;
  NumericMatrix addcovar  = RcppDeepState_NumericMatrix();
  qs::c_qsave(addcovar,"/home/akhila/fuzzer_packages/fuzzedpackages/qtl2/inst/testfiles/scan_hk_onechr_intcovar_highmem/inputs/addcovar.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "addcovar values: "<< addcovar << std::endl;
  NumericMatrix intcovar  = RcppDeepState_NumericMatrix();
  qs::c_qsave(intcovar,"/home/akhila/fuzzer_packages/fuzzedpackages/qtl2/inst/testfiles/scan_hk_onechr_intcovar_highmem/inputs/intcovar.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "intcovar values: "<< intcovar << std::endl;
  NumericVector tol(1);
  tol[0]  = RcppDeepState_double();
  qs::c_qsave(tol,"/home/akhila/fuzzer_packages/fuzzedpackages/qtl2/inst/testfiles/scan_hk_onechr_intcovar_highmem/inputs/tol.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "tol values: "<< tol << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    scan_hk_onechr_intcovar_highmem(genoprobs,pheno,addcovar,intcovar,tol[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
