// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// StrPBR_RT_In_DeepState_TestHarness_generation.cpp and StrPBR_RT_In_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

double StrPBR_RT_In(arma::mat data, double Reps, int bsize);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  std::ofstream data_stream;
  arma::mat data  = RcppDeepState_mat();
  data_stream.open("/home/akhila/fuzzer_packages/fuzzedpackages/carat/inst/testfiles/StrPBR_RT_In/inputs/data");
  data_stream << data;
  std::cout << "data values: "<< data << std::endl;
  data_stream.close();
  NumericVector Reps(1);
  Reps[0]  = RcppDeepState_double();
  qs::c_qsave(Reps,"/home/akhila/fuzzer_packages/fuzzedpackages/carat/inst/testfiles/StrPBR_RT_In/inputs/Reps.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "Reps values: "<< Reps << std::endl;
  IntegerVector bsize(1);
  bsize[0]  = RcppDeepState_int();
  qs::c_qsave(bsize,"/home/akhila/fuzzer_packages/fuzzedpackages/carat/inst/testfiles/StrPBR_RT_In/inputs/bsize.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "bsize values: "<< bsize << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    StrPBR_RT_In(data,Reps[0],bsize[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
