// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// mdmb_rcpp_oprobit_derivative_logthresh_DeepState_TestHarness_generation.cpp and mdmb_rcpp_oprobit_derivative_logthresh_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

Rcpp::NumericMatrix mdmb_rcpp_oprobit_derivative_logthresh(Rcpp::NumericVector ypred, Rcpp::NumericVector thresh_low, Rcpp::NumericVector thresh_upp, Rcpp::NumericVector y, Rcpp::NumericMatrix ll0, double eps, double h, int y_value);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector ypred  = RcppDeepState_NumericVector();
  qs::c_qsave(ypred,"/home/akhila/fuzzer_packages/fuzzedpackages/mdmb/inst/testfiles/mdmb_rcpp_oprobit_derivative_logthresh/inputs/ypred.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "ypred values: "<< ypred << std::endl;
  NumericVector thresh_low  = RcppDeepState_NumericVector();
  qs::c_qsave(thresh_low,"/home/akhila/fuzzer_packages/fuzzedpackages/mdmb/inst/testfiles/mdmb_rcpp_oprobit_derivative_logthresh/inputs/thresh_low.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "thresh_low values: "<< thresh_low << std::endl;
  NumericVector thresh_upp  = RcppDeepState_NumericVector();
  qs::c_qsave(thresh_upp,"/home/akhila/fuzzer_packages/fuzzedpackages/mdmb/inst/testfiles/mdmb_rcpp_oprobit_derivative_logthresh/inputs/thresh_upp.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "thresh_upp values: "<< thresh_upp << std::endl;
  NumericVector y  = RcppDeepState_NumericVector();
  qs::c_qsave(y,"/home/akhila/fuzzer_packages/fuzzedpackages/mdmb/inst/testfiles/mdmb_rcpp_oprobit_derivative_logthresh/inputs/y.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "y values: "<< y << std::endl;
  NumericMatrix ll0  = RcppDeepState_NumericMatrix();
  qs::c_qsave(ll0,"/home/akhila/fuzzer_packages/fuzzedpackages/mdmb/inst/testfiles/mdmb_rcpp_oprobit_derivative_logthresh/inputs/ll0.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "ll0 values: "<< ll0 << std::endl;
  NumericVector eps(1);
  eps[0]  = RcppDeepState_double();
  qs::c_qsave(eps,"/home/akhila/fuzzer_packages/fuzzedpackages/mdmb/inst/testfiles/mdmb_rcpp_oprobit_derivative_logthresh/inputs/eps.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "eps values: "<< eps << std::endl;
  NumericVector h(1);
  h[0]  = RcppDeepState_double();
  qs::c_qsave(h,"/home/akhila/fuzzer_packages/fuzzedpackages/mdmb/inst/testfiles/mdmb_rcpp_oprobit_derivative_logthresh/inputs/h.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "h values: "<< h << std::endl;
  IntegerVector y_value(1);
  y_value[0]  = RcppDeepState_int();
  qs::c_qsave(y_value,"/home/akhila/fuzzer_packages/fuzzedpackages/mdmb/inst/testfiles/mdmb_rcpp_oprobit_derivative_logthresh/inputs/y_value.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "y_value values: "<< y_value << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    mdmb_rcpp_oprobit_derivative_logthresh(ypred,thresh_low,thresh_upp,y,ll0,eps[0],h[0],y_value[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
